// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module prepareMessage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        bitlength,
        M_0_V_address0,
        M_0_V_ce0,
        M_0_V_we0,
        M_0_V_d0,
        M_1_V_address0,
        M_1_V_ce0,
        M_1_V_we0,
        M_1_V_d0,
        M_2_V_address0,
        M_2_V_ce0,
        M_2_V_we0,
        M_2_V_d0,
        M_3_V_address0,
        M_3_V_ce0,
        M_3_V_we0,
        M_3_V_d0,
        M_4_V_address0,
        M_4_V_ce0,
        M_4_V_we0,
        M_4_V_d0,
        M_5_V_address0,
        M_5_V_ce0,
        M_5_V_we0,
        M_5_V_d0,
        M_6_V_address0,
        M_6_V_ce0,
        M_6_V_we0,
        M_6_V_d0,
        M_7_V_address0,
        M_7_V_ce0,
        M_7_V_we0,
        M_7_V_d0,
        M_8_V_address0,
        M_8_V_ce0,
        M_8_V_we0,
        M_8_V_d0,
        M_9_V_address0,
        M_9_V_ce0,
        M_9_V_we0,
        M_9_V_d0,
        M_10_V_address0,
        M_10_V_ce0,
        M_10_V_we0,
        M_10_V_d0,
        M_11_V_address0,
        M_11_V_ce0,
        M_11_V_we0,
        M_11_V_d0,
        M_12_V_address0,
        M_12_V_ce0,
        M_12_V_we0,
        M_12_V_d0,
        M_13_V_address0,
        M_13_V_ce0,
        M_13_V_we0,
        M_13_V_d0,
        M_14_V_address0,
        M_14_V_ce0,
        M_14_V_we0,
        M_14_V_d0,
        M_15_V_address0,
        M_15_V_ce0,
        M_15_V_we0,
        M_15_V_d0,
        bitlength_out_din,
        bitlength_out_full_n,
        bitlength_out_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_pp0_stage0 = 10'd4;
parameter    ap_ST_fsm_state5 = 10'd8;
parameter    ap_ST_fsm_state6 = 10'd16;
parameter    ap_ST_fsm_state7 = 10'd32;
parameter    ap_ST_fsm_state8 = 10'd64;
parameter    ap_ST_fsm_state9 = 10'd128;
parameter    ap_ST_fsm_state10 = 10'd256;
parameter    ap_ST_fsm_state11 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [4:0] input_V_address0;
output   input_V_ce0;
input  [31:0] input_V_q0;
input  [31:0] bitlength;
output  [4:0] M_0_V_address0;
output   M_0_V_ce0;
output   M_0_V_we0;
output  [31:0] M_0_V_d0;
output  [4:0] M_1_V_address0;
output   M_1_V_ce0;
output   M_1_V_we0;
output  [31:0] M_1_V_d0;
output  [4:0] M_2_V_address0;
output   M_2_V_ce0;
output   M_2_V_we0;
output  [31:0] M_2_V_d0;
output  [4:0] M_3_V_address0;
output   M_3_V_ce0;
output   M_3_V_we0;
output  [31:0] M_3_V_d0;
output  [4:0] M_4_V_address0;
output   M_4_V_ce0;
output   M_4_V_we0;
output  [31:0] M_4_V_d0;
output  [4:0] M_5_V_address0;
output   M_5_V_ce0;
output   M_5_V_we0;
output  [31:0] M_5_V_d0;
output  [4:0] M_6_V_address0;
output   M_6_V_ce0;
output   M_6_V_we0;
output  [31:0] M_6_V_d0;
output  [4:0] M_7_V_address0;
output   M_7_V_ce0;
output   M_7_V_we0;
output  [31:0] M_7_V_d0;
output  [4:0] M_8_V_address0;
output   M_8_V_ce0;
output   M_8_V_we0;
output  [31:0] M_8_V_d0;
output  [4:0] M_9_V_address0;
output   M_9_V_ce0;
output   M_9_V_we0;
output  [31:0] M_9_V_d0;
output  [4:0] M_10_V_address0;
output   M_10_V_ce0;
output   M_10_V_we0;
output  [31:0] M_10_V_d0;
output  [4:0] M_11_V_address0;
output   M_11_V_ce0;
output   M_11_V_we0;
output  [31:0] M_11_V_d0;
output  [4:0] M_12_V_address0;
output   M_12_V_ce0;
output   M_12_V_we0;
output  [31:0] M_12_V_d0;
output  [4:0] M_13_V_address0;
output   M_13_V_ce0;
output   M_13_V_we0;
output  [31:0] M_13_V_d0;
output  [4:0] M_14_V_address0;
output   M_14_V_ce0;
output   M_14_V_we0;
output  [31:0] M_14_V_d0;
output  [4:0] M_15_V_address0;
output   M_15_V_ce0;
output   M_15_V_we0;
output  [31:0] M_15_V_d0;
output  [31:0] bitlength_out_din;
input   bitlength_out_full_n;
output   bitlength_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_ce0;
reg[4:0] M_0_V_address0;
reg M_0_V_ce0;
reg M_0_V_we0;
reg[31:0] M_0_V_d0;
reg[4:0] M_1_V_address0;
reg M_1_V_ce0;
reg M_1_V_we0;
reg[31:0] M_1_V_d0;
reg[4:0] M_2_V_address0;
reg M_2_V_ce0;
reg M_2_V_we0;
reg[31:0] M_2_V_d0;
reg[4:0] M_3_V_address0;
reg M_3_V_ce0;
reg M_3_V_we0;
reg[31:0] M_3_V_d0;
reg[4:0] M_4_V_address0;
reg M_4_V_ce0;
reg M_4_V_we0;
reg[31:0] M_4_V_d0;
reg[4:0] M_5_V_address0;
reg M_5_V_ce0;
reg M_5_V_we0;
reg[31:0] M_5_V_d0;
reg[4:0] M_6_V_address0;
reg M_6_V_ce0;
reg M_6_V_we0;
reg[31:0] M_6_V_d0;
reg[4:0] M_7_V_address0;
reg M_7_V_ce0;
reg M_7_V_we0;
reg[31:0] M_7_V_d0;
reg[4:0] M_8_V_address0;
reg M_8_V_ce0;
reg M_8_V_we0;
reg[31:0] M_8_V_d0;
reg[4:0] M_9_V_address0;
reg M_9_V_ce0;
reg M_9_V_we0;
reg[31:0] M_9_V_d0;
reg[4:0] M_10_V_address0;
reg M_10_V_ce0;
reg M_10_V_we0;
reg[31:0] M_10_V_d0;
reg[4:0] M_11_V_address0;
reg M_11_V_ce0;
reg M_11_V_we0;
reg[31:0] M_11_V_d0;
reg[4:0] M_12_V_address0;
reg M_12_V_ce0;
reg M_12_V_we0;
reg[31:0] M_12_V_d0;
reg[4:0] M_13_V_address0;
reg M_13_V_ce0;
reg M_13_V_we0;
reg[31:0] M_13_V_d0;
reg[4:0] M_14_V_address0;
reg M_14_V_ce0;
reg M_14_V_we0;
reg[31:0] M_14_V_d0;
reg[4:0] M_15_V_address0;
reg M_15_V_ce0;
reg M_15_V_we0;
reg[31:0] M_15_V_d0;
reg bitlength_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bitlength_out_blk_n;
reg   [27:0] i1_0_i_reg_627;
reg    ap_block_state1;
wire   [0:0] icmp_ln59_fu_661_p2;
wire    ap_CS_fsm_state2;
wire   [5:0] i_fu_667_p2;
wire   [0:0] tmp_2_fu_693_p3;
reg   [0:0] tmp_2_reg_1086;
wire   [31:0] sub_ln67_fu_700_p2;
reg   [31:0] sub_ln67_reg_1092;
wire  signed [27:0] select_ln67_fu_738_p3;
reg  signed [27:0] select_ln67_reg_1098;
wire  signed [28:0] sext_ln67_fu_746_p1;
reg  signed [28:0] sext_ln67_reg_1104;
wire   [3:0] trunc_ln67_fu_750_p1;
reg   [3:0] trunc_ln67_reg_1110;
wire   [28:0] wordlength_fu_754_p2;
reg   [28:0] wordlength_reg_1115;
wire   [0:0] icmp_ln69_fu_764_p2;
reg   [0:0] icmp_ln69_reg_1122;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [27:0] i_1_fu_769_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] zext_ln71_fu_775_p1;
reg   [63:0] zext_ln71_reg_1131;
wire   [4:0] trunc_ln74_fu_780_p1;
reg   [4:0] trunc_ln74_reg_1141;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln74_fu_783_p2;
reg   [0:0] icmp_ln74_reg_1146;
reg   [13:0] message_V_addr_2_reg_1150;
wire   [31:0] or_ln718_fu_841_p2;
reg   [31:0] or_ln718_reg_1155;
wire    ap_CS_fsm_state6;
wire   [28:0] select_ln79_fu_893_p3;
reg   [28:0] select_ln79_reg_1160;
wire    ap_CS_fsm_state7;
wire   [0:0] or_ln79_fu_911_p2;
reg   [0:0] or_ln79_reg_1166;
wire  signed [31:0] sext_ln85_1_fu_996_p1;
reg  signed [31:0] sext_ln85_1_reg_1170;
wire    ap_CS_fsm_state8;
wire   [31:0] zext_ln84_fu_1000_p1;
reg   [31:0] zext_ln84_reg_1175;
wire    ap_CS_fsm_state9;
wire   [4:0] i_2_fu_1010_p2;
reg   [4:0] i_2_reg_1183;
wire   [3:0] trunc_ln321_fu_1016_p1;
reg   [3:0] trunc_ln321_reg_1188;
wire   [0:0] icmp_ln84_fu_1004_p2;
wire   [31:0] j_fu_1025_p2;
reg   [31:0] j_reg_1195;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln85_fu_1020_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg   [13:0] message_V_address0;
reg    message_V_ce0;
reg    message_V_we0;
reg   [31:0] message_V_d0;
wire   [31:0] message_V_q0;
reg   [5:0] i_0_i_reg_616;
reg   [4:0] i2_0_i_reg_638;
reg   [31:0] j3_0_i_reg_649;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln62_fu_673_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln77_fu_789_p1;
wire   [13:0] message_V_addr_1_gep_fu_443_p3;
wire  signed [63:0] sext_ln82_fu_927_p1;
wire  signed [63:0] sext_ln80_fu_942_p1;
wire   [63:0] zext_ln87_1_fu_1042_p1;
wire   [63:0] zext_ln87_fu_1047_p1;
wire   [26:0] tmp_fu_705_p4;
wire   [27:0] zext_ln67_fu_715_p1;
wire   [26:0] tmp_1_fu_725_p4;
wire   [27:0] sub_ln67_1_fu_719_p2;
wire   [27:0] zext_ln67_1_fu_734_p1;
wire   [28:0] zext_ln69_fu_760_p1;
wire   [4:0] trunc_ln75_fu_794_p1;
wire   [5:0] tmp_3_fu_797_p3;
wire   [5:0] sub_ln75_1_fu_805_p2;
wire   [5:0] tmp_5_fu_811_p3;
wire   [5:0] select_ln75_fu_818_p3;
wire   [5:0] sub_ln75_fu_825_p2;
wire   [31:0] zext_ln75_fu_831_p1;
wire   [31:0] shl_ln75_fu_835_p2;
wire   [3:0] trunc_ln79_fu_859_p1;
wire   [3:0] trunc_ln79_1_fu_870_p1;
wire   [3:0] xor_ln79_fu_873_p2;
wire   [28:0] p_and_t1_fu_879_p3;
wire   [0:0] tmp_4_fu_852_p3;
wire   [28:0] sub_ln79_fu_887_p2;
wire   [28:0] p_and_f_fu_862_p3;
wire   [4:0] trunc_ln79_2_fu_901_p1;
wire   [0:0] icmp_ln79_fu_847_p2;
wire   [0:0] icmp_ln79_1_fu_905_p2;
wire   [28:0] add_ln82_fu_917_p2;
wire   [28:0] sub_ln82_fu_922_p2;
wire   [28:0] add_ln80_fu_932_p2;
wire   [28:0] sub_ln80_fu_937_p2;
wire   [22:0] tmp_8_fu_947_p4;
wire   [23:0] zext_ln85_fu_956_p1;
wire   [22:0] tmp_9_fu_966_p4;
wire   [23:0] sub_ln85_fu_960_p2;
wire   [23:0] zext_ln85_1_fu_975_p1;
wire   [23:0] select_ln85_fu_979_p3;
wire  signed [24:0] sext_ln85_fu_986_p1;
wire   [24:0] add_ln85_fu_990_p2;
wire   [31:0] shl_ln87_fu_1031_p2;
wire   [31:0] add_ln87_fu_1037_p2;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

prepareMessage_mebkb #(
    .DataWidth( 32 ),
    .AddressRange( 10000 ),
    .AddressWidth( 14 ))
message_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(message_V_address0),
    .ce0(message_V_ce0),
    .we0(message_V_we0),
    .d0(message_V_d0),
    .q0(message_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln84_fu_1004_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_764_p2 == 1'd1))) begin
        i1_0_i_reg_627 <= i_1_fu_769_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd1))) begin
        i1_0_i_reg_627 <= 28'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln85_fu_1020_p2 == 1'd1))) begin
        i2_0_i_reg_638 <= i_2_reg_1183;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i2_0_i_reg_638 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0))) begin
        i_0_i_reg_616 <= i_fu_667_p2;
    end else if ((~((bitlength_out_full_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_616 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        j3_0_i_reg_649 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        j3_0_i_reg_649 <= j_reg_1195;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_2_reg_1183 <= i_2_fu_1010_p2;
        zext_ln84_reg_1175[4 : 0] <= zext_ln84_fu_1000_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln69_reg_1122 <= icmp_ln69_fu_764_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln74_reg_1146 <= icmp_ln74_fu_783_p2;
        trunc_ln74_reg_1141 <= trunc_ln74_fu_780_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_reg_1195 <= j_fu_1025_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln74_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        message_V_addr_2_reg_1150 <= sext_ln77_fu_789_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        or_ln718_reg_1155 <= or_ln718_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        or_ln79_reg_1166 <= or_ln79_fu_911_p2;
        select_ln79_reg_1160 <= select_ln79_fu_893_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd1))) begin
        select_ln67_reg_1098 <= select_ln67_fu_738_p3;
        sext_ln67_reg_1104 <= sext_ln67_fu_746_p1;
        sub_ln67_reg_1092 <= sub_ln67_fu_700_p2;
        tmp_2_reg_1086 <= bitlength[32'd31];
        trunc_ln67_reg_1110 <= trunc_ln67_fu_750_p1;
        wordlength_reg_1115 <= wordlength_fu_754_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sext_ln85_1_reg_1170 <= sext_ln85_1_fu_996_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        trunc_ln321_reg_1188 <= trunc_ln321_fu_1016_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_fu_764_p2 == 1'd1))) begin
        zext_ln71_reg_1131[27 : 0] <= zext_ln71_fu_775_p1[27 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_0_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_0_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_0_V_ce0 = 1'b1;
    end else begin
        M_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_0_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_0_V_d0 = 32'd0;
    end else begin
        M_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd0) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_0_V_we0 = 1'b1;
    end else begin
        M_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_10_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_10_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_10_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_10_V_ce0 = 1'b1;
    end else begin
        M_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_10_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_10_V_d0 = 32'd0;
    end else begin
        M_10_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd10) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_10_V_we0 = 1'b1;
    end else begin
        M_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_11_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_11_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_11_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_11_V_ce0 = 1'b1;
    end else begin
        M_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_11_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_11_V_d0 = 32'd0;
    end else begin
        M_11_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd11) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_11_V_we0 = 1'b1;
    end else begin
        M_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_12_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_12_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_12_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_12_V_ce0 = 1'b1;
    end else begin
        M_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_12_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_12_V_d0 = 32'd0;
    end else begin
        M_12_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd12) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_12_V_we0 = 1'b1;
    end else begin
        M_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_13_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_13_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_13_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_13_V_ce0 = 1'b1;
    end else begin
        M_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_13_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_13_V_d0 = 32'd0;
    end else begin
        M_13_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd13) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_13_V_we0 = 1'b1;
    end else begin
        M_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_14_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_14_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_14_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_14_V_ce0 = 1'b1;
    end else begin
        M_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_14_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_14_V_d0 = 32'd0;
    end else begin
        M_14_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd14) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_14_V_we0 = 1'b1;
    end else begin
        M_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_15_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_15_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_15_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_15_V_ce0 = 1'b1;
    end else begin
        M_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_15_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_15_V_d0 = 32'd0;
    end else begin
        M_15_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd15) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_15_V_we0 = 1'b1;
    end else begin
        M_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_1_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_1_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_1_V_ce0 = 1'b1;
    end else begin
        M_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_1_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_1_V_d0 = 32'd0;
    end else begin
        M_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_1_V_we0 = 1'b1;
    end else begin
        M_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_2_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_2_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_2_V_ce0 = 1'b1;
    end else begin
        M_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_2_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_2_V_d0 = 32'd0;
    end else begin
        M_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd2) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_2_V_we0 = 1'b1;
    end else begin
        M_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_3_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_3_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_3_V_ce0 = 1'b1;
    end else begin
        M_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_3_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_3_V_d0 = 32'd0;
    end else begin
        M_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd3) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_3_V_we0 = 1'b1;
    end else begin
        M_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_4_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_4_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_4_V_ce0 = 1'b1;
    end else begin
        M_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_4_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_4_V_d0 = 32'd0;
    end else begin
        M_4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd4) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_4_V_we0 = 1'b1;
    end else begin
        M_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_5_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_5_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_5_V_ce0 = 1'b1;
    end else begin
        M_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_5_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_5_V_d0 = 32'd0;
    end else begin
        M_5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd5) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_5_V_we0 = 1'b1;
    end else begin
        M_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_6_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_6_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_6_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_6_V_ce0 = 1'b1;
    end else begin
        M_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_6_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_6_V_d0 = 32'd0;
    end else begin
        M_6_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd6) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_6_V_we0 = 1'b1;
    end else begin
        M_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_7_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_7_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_7_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_7_V_ce0 = 1'b1;
    end else begin
        M_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_7_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_7_V_d0 = 32'd0;
    end else begin
        M_7_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd7) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_7_V_we0 = 1'b1;
    end else begin
        M_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_8_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_8_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_8_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_8_V_ce0 = 1'b1;
    end else begin
        M_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_8_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_8_V_d0 = 32'd0;
    end else begin
        M_8_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd8) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_8_V_we0 = 1'b1;
    end else begin
        M_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_9_V_address0 = zext_ln87_fu_1047_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_9_V_address0 = zext_ln62_fu_673_p1;
    end else begin
        M_9_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        M_9_V_ce0 = 1'b1;
    end else begin
        M_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        M_9_V_d0 = message_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        M_9_V_d0 = 32'd0;
    end else begin
        M_9_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln321_reg_1188 == 4'd9) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd0)))) begin
        M_9_V_we0 = 1'b1;
    end else begin
        M_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln69_fu_764_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln84_fu_1004_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln84_fu_1004_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bitlength_out_blk_n = bitlength_out_full_n;
    end else begin
        bitlength_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bitlength_out_full_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bitlength_out_write = 1'b1;
    end else begin
        bitlength_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        message_V_address0 = zext_ln87_1_fu_1042_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (or_ln79_reg_1166 == 1'd1))) begin
        message_V_address0 = sext_ln80_fu_942_p1;
    end else if (((or_ln79_reg_1166 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        message_V_address0 = sext_ln82_fu_927_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        message_V_address0 = message_V_addr_2_reg_1150;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln74_fu_783_p2 == 1'd1))) begin
        message_V_address0 = message_V_addr_1_gep_fu_443_p3;
    end else if (((icmp_ln74_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        message_V_address0 = sext_ln77_fu_789_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        message_V_address0 = zext_ln71_reg_1131;
    end else begin
        message_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state8) & (or_ln79_reg_1166 == 1'd1)) | ((or_ln79_reg_1166 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln74_fu_783_p2 == 1'd1)) | ((icmp_ln74_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        message_V_ce0 = 1'b1;
    end else begin
        message_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state8) & (or_ln79_reg_1166 == 1'd1)) | ((or_ln79_reg_1166 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        message_V_d0 = bitlength;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        message_V_d0 = or_ln718_reg_1155;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln74_fu_783_p2 == 1'd1))) begin
        message_V_d0 = 32'd2147483648;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        message_V_d0 = input_V_q0;
    end else begin
        message_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state8) & (or_ln79_reg_1166 == 1'd1)) | ((or_ln79_reg_1166 == 1'd0) & (1'b1 == ap_CS_fsm_state8)) | ((icmp_ln74_reg_1146 == 1'd0) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln74_fu_783_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln69_reg_1122 == 1'd1)))) begin
        message_V_we0 = 1'b1;
    end else begin
        message_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bitlength_out_full_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln59_fu_661_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_764_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln69_fu_764_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln74_fu_783_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln84_fu_1004_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln85_fu_1020_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln80_fu_932_p2 = ($signed(sext_ln67_reg_1104) + $signed(29'd32));

assign add_ln82_fu_917_p2 = ($signed(sext_ln67_reg_1104) + $signed(29'd16));

assign add_ln85_fu_990_p2 = ($signed(sext_ln85_fu_986_p1) + $signed(25'd1));

assign add_ln87_fu_1037_p2 = (shl_ln87_fu_1031_p2 + zext_ln84_reg_1175);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((bitlength_out_full_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bitlength_out_din = bitlength;

assign i_1_fu_769_p2 = (i1_0_i_reg_627 + 28'd1);

assign i_2_fu_1010_p2 = (i2_0_i_reg_638 + 5'd1);

assign i_fu_667_p2 = (i_0_i_reg_616 + 6'd1);

assign icmp_ln59_fu_661_p2 = ((i_0_i_reg_616 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_764_p2 = (($signed(zext_ln69_fu_760_p1) < $signed(wordlength_reg_1115)) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_783_p2 = ((trunc_ln74_fu_780_p1 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln79_1_fu_905_p2 = ((trunc_ln79_2_fu_901_p1 == 5'd15) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_847_p2 = ((trunc_ln67_reg_1110 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln84_fu_1004_p2 = ((i2_0_i_reg_638 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_1020_p2 = (($signed(j3_0_i_reg_649) > $signed(sext_ln85_1_reg_1170)) ? 1'b1 : 1'b0);

assign input_V_address0 = zext_ln71_fu_775_p1;

assign j_fu_1025_p2 = (j3_0_i_reg_649 + 32'd1);

assign message_V_addr_1_gep_fu_443_p3 = sext_ln77_fu_789_p1;

assign or_ln718_fu_841_p2 = (shl_ln75_fu_835_p2 | message_V_q0);

assign or_ln79_fu_911_p2 = (icmp_ln79_fu_847_p2 | icmp_ln79_1_fu_905_p2);

assign p_and_f_fu_862_p3 = {{25'd0}, {trunc_ln79_fu_859_p1}};

assign p_and_t1_fu_879_p3 = {{25'd0}, {xor_ln79_fu_873_p2}};

assign select_ln67_fu_738_p3 = ((tmp_2_fu_693_p3[0:0] === 1'b1) ? sub_ln67_1_fu_719_p2 : zext_ln67_1_fu_734_p1);

assign select_ln75_fu_818_p3 = ((tmp_2_reg_1086[0:0] === 1'b1) ? sub_ln75_1_fu_805_p2 : tmp_5_fu_811_p3);

assign select_ln79_fu_893_p3 = ((tmp_4_fu_852_p3[0:0] === 1'b1) ? sub_ln79_fu_887_p2 : p_and_f_fu_862_p3);

assign select_ln85_fu_979_p3 = ((tmp_2_reg_1086[0:0] === 1'b1) ? sub_ln85_fu_960_p2 : zext_ln85_1_fu_975_p1);

assign sext_ln67_fu_746_p1 = select_ln67_fu_738_p3;

assign sext_ln77_fu_789_p1 = select_ln67_reg_1098;

assign sext_ln80_fu_942_p1 = $signed(sub_ln80_fu_937_p2);

assign sext_ln82_fu_927_p1 = $signed(sub_ln82_fu_922_p2);

assign sext_ln85_1_fu_996_p1 = $signed(add_ln85_fu_990_p2);

assign sext_ln85_fu_986_p1 = $signed(select_ln85_fu_979_p3);

assign shl_ln75_fu_835_p2 = 32'd1 << zext_ln75_fu_831_p1;

assign shl_ln87_fu_1031_p2 = j3_0_i_reg_649 << 32'd4;

assign sub_ln67_1_fu_719_p2 = (28'd0 - zext_ln67_fu_715_p1);

assign sub_ln67_fu_700_p2 = (32'd0 - bitlength);

assign sub_ln75_1_fu_805_p2 = (6'd0 - tmp_3_fu_797_p3);

assign sub_ln75_fu_825_p2 = (6'd31 - select_ln75_fu_818_p3);

assign sub_ln79_fu_887_p2 = (29'd0 - p_and_t1_fu_879_p3);

assign sub_ln80_fu_937_p2 = (add_ln80_fu_932_p2 - select_ln79_reg_1160);

assign sub_ln82_fu_922_p2 = (add_ln82_fu_917_p2 - select_ln79_reg_1160);

assign sub_ln85_fu_960_p2 = (24'd0 - zext_ln85_fu_956_p1);

assign tmp_1_fu_725_p4 = {{bitlength[31:5]}};

assign tmp_2_fu_693_p3 = bitlength[32'd31];

assign tmp_3_fu_797_p3 = {{1'd0}, {trunc_ln75_fu_794_p1}};

assign tmp_4_fu_852_p3 = wordlength_reg_1115[32'd28];

assign tmp_5_fu_811_p3 = {{1'd0}, {trunc_ln74_reg_1141}};

assign tmp_8_fu_947_p4 = {{sub_ln67_reg_1092[31:9]}};

assign tmp_9_fu_966_p4 = {{bitlength[31:9]}};

assign tmp_fu_705_p4 = {{sub_ln67_fu_700_p2[31:5]}};

assign trunc_ln321_fu_1016_p1 = i2_0_i_reg_638[3:0];

assign trunc_ln67_fu_750_p1 = select_ln67_fu_738_p3[3:0];

assign trunc_ln74_fu_780_p1 = bitlength[4:0];

assign trunc_ln75_fu_794_p1 = sub_ln67_reg_1092[4:0];

assign trunc_ln79_1_fu_870_p1 = select_ln67_reg_1098[3:0];

assign trunc_ln79_2_fu_901_p1 = select_ln79_fu_893_p3[4:0];

assign trunc_ln79_fu_859_p1 = wordlength_reg_1115[3:0];

assign wordlength_fu_754_p2 = ($signed(29'd1) + $signed(sext_ln67_fu_746_p1));

assign xor_ln79_fu_873_p2 = (trunc_ln79_1_fu_870_p1 ^ 4'd15);

assign zext_ln62_fu_673_p1 = i_0_i_reg_616;

assign zext_ln67_1_fu_734_p1 = tmp_1_fu_725_p4;

assign zext_ln67_fu_715_p1 = tmp_fu_705_p4;

assign zext_ln69_fu_760_p1 = i1_0_i_reg_627;

assign zext_ln71_fu_775_p1 = i1_0_i_reg_627;

assign zext_ln75_fu_831_p1 = sub_ln75_fu_825_p2;

assign zext_ln84_fu_1000_p1 = i2_0_i_reg_638;

assign zext_ln85_1_fu_975_p1 = tmp_9_fu_966_p4;

assign zext_ln85_fu_956_p1 = tmp_8_fu_947_p4;

assign zext_ln87_1_fu_1042_p1 = add_ln87_fu_1037_p2;

assign zext_ln87_fu_1047_p1 = j3_0_i_reg_649;

always @ (posedge ap_clk) begin
    zext_ln71_reg_1131[63:28] <= 36'b000000000000000000000000000000000000;
    zext_ln84_reg_1175[31:5] <= 27'b000000000000000000000000000;
end

endmodule //prepareMessage
