// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dut,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.625000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=78,HLS_SYN_DSP=0,HLS_SYN_FF=2992,HLS_SYN_LUT=5272,HLS_VERSION=2019_2}" *)

module dut (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        strm_in_V_V_dout,
        strm_in_V_V_empty_n,
        strm_in_V_V_read,
        strm_out_V_V_din,
        strm_out_V_V_full_n,
        strm_out_V_V_write
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] strm_in_V_V_dout;
input   strm_in_V_V_empty_n;
output   strm_in_V_V_read;
output  [31:0] strm_out_V_V_din;
input   strm_out_V_V_full_n;
output   strm_out_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg strm_in_V_V_read;
reg[31:0] strm_out_V_V_din;
reg strm_out_V_V_write;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    strm_in_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln37_fu_256_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln43_fu_273_p2;
wire    ap_CS_fsm_state5;
reg    strm_out_V_V_blk_n;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln24_fu_295_p2;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg   [31:0] tmp_V_reg_307;
reg    ap_block_state1;
reg   [31:0] tmp_V_15_reg_312;
wire   [3:0] i_fu_262_p2;
reg    ap_block_state3;
wire   [3:0] i_15_fu_279_p2;
reg    ap_block_state4;
reg   [31:0] tmp_V_16_reg_333;
reg   [31:0] tmp_V_17_reg_338;
wire   [31:0] grp_mineblock_fu_238_ap_return;
reg   [31:0] output_nonce_V_reg_343;
wire    ap_CS_fsm_state6;
wire    grp_mineblock_fu_238_ap_ready;
wire    grp_mineblock_fu_238_ap_done;
wire   [63:0] zext_ln24_fu_290_p1;
reg   [63:0] zext_ln24_reg_348;
reg    ap_block_state7;
wire   [3:0] p_i0_fu_301_p2;
reg   [3:0] p_i0_reg_356;
reg   [2:0] prevhash_V_address0;
reg    prevhash_V_ce0;
reg    prevhash_V_we0;
wire   [31:0] prevhash_V_q0;
reg   [2:0] merkle_root_V_address0;
reg    merkle_root_V_ce0;
reg    merkle_root_V_we0;
wire   [31:0] merkle_root_V_q0;
reg   [2:0] output_hash_V_address0;
reg    output_hash_V_ce0;
reg    output_hash_V_we0;
wire   [31:0] output_hash_V_q0;
reg   [2:0] p_1_address0;
reg    p_1_ce0;
reg    p_1_we0;
wire   [31:0] p_1_q0;
wire    grp_mineblock_fu_238_ap_start;
wire    grp_mineblock_fu_238_ap_idle;
wire   [2:0] grp_mineblock_fu_238_agg_result_hash_V_address0;
wire    grp_mineblock_fu_238_agg_result_hash_V_ce0;
wire    grp_mineblock_fu_238_agg_result_hash_V_we0;
wire   [31:0] grp_mineblock_fu_238_agg_result_hash_V_d0;
wire   [2:0] grp_mineblock_fu_238_prevhash_V_address0;
wire    grp_mineblock_fu_238_prevhash_V_ce0;
wire   [2:0] grp_mineblock_fu_238_merkle_root_V_address0;
wire    grp_mineblock_fu_238_merkle_root_V_ce0;
reg   [3:0] i2_0_reg_205;
reg   [3:0] i4_0_reg_216;
reg   [3:0] p_i0_0_i_reg_227;
wire    ap_CS_fsm_state8;
reg    grp_mineblock_fu_238_ap_start_reg;
wire   [63:0] zext_ln38_fu_268_p1;
wire   [63:0] zext_ln44_fu_285_p1;
reg   [15:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_mineblock_fu_238_ap_start_reg = 1'b0;
end

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
prevhash_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(prevhash_V_address0),
    .ce0(prevhash_V_ce0),
    .we0(prevhash_V_we0),
    .d0(strm_in_V_V_dout),
    .q0(prevhash_V_q0)
);

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
merkle_root_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(merkle_root_V_address0),
    .ce0(merkle_root_V_ce0),
    .we0(merkle_root_V_we0),
    .d0(strm_in_V_V_dout),
    .q0(merkle_root_V_q0)
);

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
output_hash_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(output_hash_V_address0),
    .ce0(output_hash_V_ce0),
    .we0(output_hash_V_we0),
    .d0(p_1_q0),
    .q0(output_hash_V_q0)
);

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_1_address0),
    .ce0(p_1_ce0),
    .we0(p_1_we0),
    .d0(grp_mineblock_fu_238_agg_result_hash_V_d0),
    .q0(p_1_q0)
);

mineblock grp_mineblock_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mineblock_fu_238_ap_start),
    .ap_done(grp_mineblock_fu_238_ap_done),
    .ap_idle(grp_mineblock_fu_238_ap_idle),
    .ap_ready(grp_mineblock_fu_238_ap_ready),
    .agg_result_hash_V_address0(grp_mineblock_fu_238_agg_result_hash_V_address0),
    .agg_result_hash_V_ce0(grp_mineblock_fu_238_agg_result_hash_V_ce0),
    .agg_result_hash_V_we0(grp_mineblock_fu_238_agg_result_hash_V_we0),
    .agg_result_hash_V_d0(grp_mineblock_fu_238_agg_result_hash_V_d0),
    .noncestart_V(tmp_V_reg_307),
    .version_0_V_read(tmp_V_15_reg_312),
    .prevhash_V_address0(grp_mineblock_fu_238_prevhash_V_address0),
    .prevhash_V_ce0(grp_mineblock_fu_238_prevhash_V_ce0),
    .prevhash_V_q0(prevhash_V_q0),
    .merkle_root_V_address0(grp_mineblock_fu_238_merkle_root_V_address0),
    .merkle_root_V_ce0(grp_mineblock_fu_238_merkle_root_V_ce0),
    .merkle_root_V_q0(merkle_root_V_q0),
    .time_0_V_read(tmp_V_16_reg_333),
    .nbits_0_V_read(tmp_V_17_reg_338),
    .ap_return(grp_mineblock_fu_238_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mineblock_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_mineblock_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_mineblock_fu_238_ap_ready == 1'b1)) begin
            grp_mineblock_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        i2_0_reg_205 <= 4'd0;
    end else if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i2_0_reg_205 <= i_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i4_0_reg_216 <= 4'd0;
    end else if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i4_0_reg_216 <= i_15_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_i0_0_i_reg_227 <= p_i0_reg_356;
    end else if (((1'b1 == ap_CS_fsm_state6) & (grp_mineblock_fu_238_ap_done == 1'b1))) begin
        p_i0_0_i_reg_227 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_mineblock_fu_238_ap_done == 1'b1))) begin
        output_nonce_V_reg_343 <= grp_mineblock_fu_238_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_i0_reg_356 <= p_i0_fu_301_p2;
        zext_ln24_reg_348[3 : 0] <= zext_ln24_fu_290_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_15_reg_312 <= strm_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_V_16_reg_333 <= strm_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_V_17_reg_338 <= strm_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((strm_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_V_reg_307 <= strm_in_V_V_dout;
    end
end

always @ (*) begin
    if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        merkle_root_V_address0 = zext_ln44_fu_285_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        merkle_root_V_address0 = grp_mineblock_fu_238_merkle_root_V_address0;
    end else begin
        merkle_root_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state4))) begin
        merkle_root_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        merkle_root_V_ce0 = grp_mineblock_fu_238_merkle_root_V_ce0;
    end else begin
        merkle_root_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        merkle_root_V_we0 = 1'b1;
    end else begin
        merkle_root_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_hash_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_hash_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        output_hash_V_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_hash_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        output_hash_V_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_hash_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_hash_V_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_hash_V_address0 = zext_ln24_reg_348;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        output_hash_V_address0 = 64'd7;
    end else begin
        output_hash_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | (~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        output_hash_V_ce0 = 1'b1;
    end else begin
        output_hash_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        output_hash_V_we0 = 1'b1;
    end else begin
        output_hash_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_1_address0 = zext_ln24_fu_290_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_1_address0 = grp_mineblock_fu_238_agg_result_hash_V_address0;
    end else begin
        p_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_1_ce0 = grp_mineblock_fu_238_agg_result_hash_V_ce0;
    end else begin
        p_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_1_we0 = grp_mineblock_fu_238_agg_result_hash_V_we0;
    end else begin
        p_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        prevhash_V_address0 = zext_ln38_fu_268_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        prevhash_V_address0 = grp_mineblock_fu_238_prevhash_V_address0;
    end else begin
        prevhash_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        prevhash_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        prevhash_V_ce0 = grp_mineblock_fu_238_prevhash_V_ce0;
    end else begin
        prevhash_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        prevhash_V_we0 = 1'b1;
    end else begin
        prevhash_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | ((icmp_ln43_fu_273_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln37_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        strm_in_V_V_blk_n = strm_in_V_V_empty_n;
    end else begin
        strm_in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | (~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | (~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | (~((strm_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        strm_in_V_V_read = 1'b1;
    end else begin
        strm_in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | ((icmp_ln24_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)))) begin
        strm_out_V_V_blk_n = strm_out_V_V_full_n;
    end else begin
        strm_out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        strm_out_V_V_din = output_hash_V_q0;
    end else if ((~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (icmp_ln24_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        strm_out_V_V_din = output_nonce_V_reg_343;
    end else begin
        strm_out_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | (~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (icmp_ln24_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        strm_out_V_V_write = 1'b1;
    end else begin
        strm_out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((strm_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)) & (icmp_ln37_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~(((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0))) & (icmp_ln43_fu_273_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((strm_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_mineblock_fu_238_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (icmp_ln24_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if ((~((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0)) & (icmp_ln24_fu_295_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((strm_out_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((strm_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln37_fu_256_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = (((icmp_ln43_fu_273_p2 == 1'd1) & (strm_in_V_V_empty_n == 1'b0)) | ((icmp_ln43_fu_273_p2 == 1'd0) & (strm_in_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state7 = ((icmp_ln24_fu_295_p2 == 1'd1) & (strm_out_V_V_full_n == 1'b0));
end

assign grp_mineblock_fu_238_ap_start = grp_mineblock_fu_238_ap_start_reg;

assign i_15_fu_279_p2 = (i4_0_reg_216 + 4'd1);

assign i_fu_262_p2 = (i2_0_reg_205 + 4'd1);

assign icmp_ln24_fu_295_p2 = ((p_i0_0_i_reg_227 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_256_p2 = ((i2_0_reg_205 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_273_p2 = ((i4_0_reg_216 == 4'd8) ? 1'b1 : 1'b0);

assign p_i0_fu_301_p2 = (p_i0_0_i_reg_227 + 4'd1);

assign zext_ln24_fu_290_p1 = p_i0_0_i_reg_227;

assign zext_ln38_fu_268_p1 = i2_0_reg_205;

assign zext_ln44_fu_285_p1 = i4_0_reg_216;

always @ (posedge ap_clk) begin
    zext_ln24_reg_348[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //dut
