// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hash1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        outputlocation_V_address0,
        outputlocation_V_ce0,
        outputlocation_V_we0,
        outputlocation_V_d0
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] input_V_address0;
output   input_V_ce0;
input  [31:0] input_V_q0;
output  [2:0] outputlocation_V_address0;
output   outputlocation_V_ce0;
output   outputlocation_V_we0;
output  [31:0] outputlocation_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_ce0;
reg outputlocation_V_ce0;
reg outputlocation_V_we0;

(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] H_0_V_address0;
reg    H_0_V_ce0;
wire   [31:0] H_0_V_q0;
wire   [5:0] K_address0;
reg    K_ce0;
wire   [31:0] K_q0;
wire   [31:0] W_V_q0;
reg   [31:0] reg_659;
wire    ap_CS_fsm_state15;
wire   [31:0] W_V_q1;
wire    ap_CS_fsm_state16;
wire   [3:0] i_fu_670_p2;
reg   [3:0] i_reg_1580;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln80_fu_676_p1;
reg   [63:0] zext_ln80_reg_1585;
wire   [0:0] icmp_ln79_fu_664_p2;
wire   [4:0] i_11_fu_687_p2;
reg   [4:0] i_11_reg_1598;
wire    ap_CS_fsm_state4;
wire   [6:0] zext_ln1598_fu_693_p1;
reg   [6:0] zext_ln1598_reg_1603;
wire   [0:0] icmp_ln104_fu_681_p2;
wire   [1:0] j_fu_703_p2;
reg   [1:0] j_reg_1611;
wire    ap_CS_fsm_state5;
wire   [6:0] add_ln321_fu_721_p2;
reg   [6:0] add_ln321_reg_1616;
wire   [0:0] icmp_ln105_fu_697_p2;
wire   [3:0] i_12_fu_759_p2;
reg   [3:0] i_12_reg_1629;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln111_fu_765_p1;
reg   [63:0] zext_ln111_reg_1634;
wire   [0:0] icmp_ln110_fu_753_p2;
wire   [1:0] add_ln116_fu_776_p2;
reg   [1:0] add_ln116_reg_1647;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln114_fu_770_p2;
wire   [4:0] tmp_18_fu_782_p3;
reg   [4:0] tmp_18_reg_1652;
wire    ap_CS_fsm_state10;
wire   [31:0] H_V_q0;
reg   [31:0] a_V_reg_1682;
wire   [31:0] H_V_q1;
reg   [31:0] b_V_reg_1688;
wire    ap_CS_fsm_state11;
reg   [31:0] c_V_reg_1704;
reg   [31:0] d_V_reg_1710;
wire    ap_CS_fsm_state12;
reg   [31:0] e_V_reg_1726;
reg   [31:0] f_V_reg_1732;
wire   [6:0] zext_ln116_2_fu_901_p1;
reg   [6:0] zext_ln116_2_reg_1738;
wire    ap_CS_fsm_state13;
reg   [31:0] g_V_reg_1743;
reg   [31:0] h_V_reg_1749;
wire   [6:0] j_2_fu_911_p2;
reg   [6:0] j_2_reg_1758;
wire    ap_CS_fsm_state14;
wire   [31:0] ch_V_fu_935_p2;
reg   [31:0] ch_V_reg_1763;
wire   [0:0] icmp_ln127_fu_905_p2;
wire   [31:0] maj_V_fu_959_p2;
reg   [31:0] maj_V_reg_1768;
wire   [31:0] ret_V_42_fu_1037_p2;
reg   [31:0] ret_V_42_reg_1773;
wire   [31:0] ret_V_46_fu_1115_p2;
reg   [31:0] ret_V_46_reg_1778;
wire   [0:0] icmp_ln134_fu_1131_p2;
reg   [0:0] icmp_ln134_reg_1783;
wire   [63:0] zext_ln135_fu_1137_p1;
reg   [63:0] zext_ln135_reg_1787;
wire   [4:0] tmp_26_fu_1173_p3;
reg   [4:0] tmp_26_reg_1810;
wire   [31:0] add_ln209_2_fu_1213_p2;
reg   [31:0] add_ln209_2_reg_1820;
wire   [31:0] add_ln209_4_fu_1218_p2;
reg   [31:0] add_ln209_4_reg_1825;
wire   [31:0] add_ln209_5_fu_1223_p2;
reg   [31:0] add_ln209_5_reg_1830;
wire   [31:0] add_ln209_6_fu_1228_p2;
reg   [31:0] add_ln209_6_reg_1835;
wire   [1:0] i_14_fu_1233_p2;
reg   [1:0] i_14_reg_1840;
reg   [31:0] W_V_load_1_reg_1845;
wire   [31:0] add_ln209_19_fu_1401_p2;
reg   [31:0] add_ln209_19_reg_1860;
wire   [31:0] add_ln209_22_fu_1423_p2;
reg   [31:0] add_ln209_22_reg_1865;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state19;
wire   [5:0] W_V_addr_6_gep_fu_422_p3;
wire   [31:0] T1_V_fu_1434_p2;
reg   [31:0] T1_V_reg_1880;
wire    ap_CS_fsm_state20;
wire   [31:0] e_V_2_fu_1439_p2;
wire    ap_CS_fsm_state21;
wire   [31:0] a_V_2_fu_1448_p2;
wire   [3:0] i_13_fu_1555_p2;
reg   [3:0] i_13_reg_1899;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln161_fu_1549_p2;
reg   [13:0] message_V_address0;
reg    message_V_ce0;
reg    message_V_we0;
reg   [31:0] message_V_d0;
reg   [13:0] message_V_address1;
reg    message_V_ce1;
reg    message_V_we1;
wire   [31:0] message_V_q1;
reg   [8:0] M_V_address0;
reg    M_V_ce0;
reg    M_V_we0;
wire   [31:0] M_V_q0;
reg   [7:0] H_V_address0;
reg    H_V_ce0;
reg    H_V_we0;
reg   [31:0] H_V_d0;
reg   [7:0] H_V_address1;
reg    H_V_ce1;
reg    H_V_we1;
reg   [31:0] H_V_d1;
reg   [5:0] W_V_address0;
reg    W_V_ce0;
reg    W_V_we0;
wire   [31:0] W_V_d0;
reg   [5:0] W_V_address1;
reg    W_V_ce1;
reg    W_V_we1;
reg   [3:0] i_0_reg_492;
wire    ap_CS_fsm_state3;
reg   [4:0] i4_0_reg_503;
reg   [1:0] i_op_assign_reg_515;
wire    ap_CS_fsm_state6;
reg   [3:0] i9_0_reg_526;
wire    ap_CS_fsm_state8;
reg   [1:0] i_op_assign_2_reg_537;
wire    ap_CS_fsm_state24;
reg   [31:0] b_V_2_reg_549;
reg   [31:0] c_V_2_reg_559;
reg   [31:0] d_V_2_reg_570;
reg   [31:0] p_0622_0_reg_581;
reg   [31:0] f_V_2_reg_592;
reg   [31:0] g_V_2_reg_602;
reg   [31:0] h_V_2_reg_613;
reg   [31:0] p_0657_0_reg_624;
reg   [6:0] j12_0_reg_635;
reg   [3:0] i13_0_reg_647;
wire    ap_CS_fsm_state26;
wire   [63:0] zext_ln106_fu_744_p1;
wire   [63:0] zext_ln321_5_fu_749_p1;
wire   [63:0] zext_ln116_fu_790_p1;
wire   [63:0] tmp_19_fu_801_p3;
wire   [63:0] tmp_20_fu_815_p3;
wire   [63:0] tmp_21_fu_829_p3;
wire   [63:0] tmp_22_fu_843_p3;
wire   [63:0] tmp_23_fu_857_p3;
wire   [63:0] tmp_24_fu_871_p3;
wire   [63:0] tmp_25_fu_885_p3;
wire   [63:0] zext_ln321_7_fu_1146_p1;
wire   [63:0] zext_ln137_fu_1157_p1;
wire   [63:0] zext_ln137_4_fu_1168_p1;
wire   [63:0] zext_ln321_4_fu_1181_p1;
wire   [63:0] tmp_27_fu_1192_p3;
wire   [63:0] zext_ln137_5_fu_1245_p1;
wire   [63:0] zext_ln137_6_fu_1256_p1;
wire    ap_CS_fsm_state18;
wire   [63:0] tmp_28_fu_1458_p3;
wire    ap_CS_fsm_state22;
wire   [63:0] tmp_29_fu_1472_p3;
wire   [63:0] tmp_30_fu_1492_p3;
wire    ap_CS_fsm_state23;
wire   [63:0] tmp_31_fu_1506_p3;
wire   [63:0] tmp_32_fu_1520_p3;
wire   [63:0] tmp_33_fu_1534_p3;
wire   [63:0] zext_ln321_6_fu_1567_p1;
wire   [63:0] zext_ln162_fu_1572_p1;
wire   [31:0] add_ln209_fu_1201_p2;
wire   [31:0] add_ln209_1_fu_1207_p2;
wire   [31:0] add_ln209_3_fu_1481_p2;
wire   [31:0] add_ln209_7_fu_1543_p2;
wire   [5:0] tmp_fu_709_p3;
wire   [6:0] zext_ln321_fu_717_p1;
wire   [0:0] trunc_ln106_fu_726_p1;
wire   [4:0] shl_ln_fu_730_p3;
wire   [4:0] add_ln106_fu_738_p2;
wire   [4:0] or_ln117_fu_795_p2;
wire   [4:0] or_ln118_fu_810_p2;
wire   [4:0] or_ln119_fu_824_p2;
wire   [4:0] or_ln120_fu_838_p2;
wire   [4:0] or_ln121_fu_852_p2;
wire   [4:0] or_ln122_fu_866_p2;
wire   [4:0] or_ln123_fu_880_p2;
wire   [5:0] tmp_s_fu_894_p3;
wire   [31:0] xor_ln26_fu_923_p2;
wire   [31:0] and_ln26_2_fu_929_p2;
wire   [31:0] and_ln26_fu_917_p2;
wire   [31:0] xor_ln31_fu_941_p2;
wire   [31:0] and_ln31_fu_947_p2;
wire   [31:0] and_ln31_2_fu_953_p2;
wire   [1:0] trunc_ln1503_fu_975_p1;
wire   [29:0] r_V_fu_965_p4;
wire   [12:0] trunc_ln1503_10_fu_997_p1;
wire   [18:0] r_V_s_fu_987_p4;
wire   [21:0] trunc_ln1503_11_fu_1019_p1;
wire   [9:0] r_V_11_fu_1009_p4;
wire   [31:0] ret_V_39_fu_979_p3;
wire   [31:0] ret_V_41_fu_1023_p3;
wire   [31:0] xor_ln1357_fu_1031_p2;
wire   [31:0] ret_V_40_fu_1001_p3;
wire   [5:0] trunc_ln1503_12_fu_1053_p1;
wire   [25:0] r_V_12_fu_1043_p4;
wire   [10:0] trunc_ln1503_13_fu_1075_p1;
wire   [20:0] r_V_13_fu_1065_p4;
wire   [24:0] trunc_ln1503_14_fu_1097_p1;
wire   [6:0] r_V_14_fu_1087_p4;
wire   [31:0] ret_V_43_fu_1057_p3;
wire   [31:0] ret_V_45_fu_1101_p3;
wire   [31:0] xor_ln1357_9_fu_1109_p2;
wire   [31:0] ret_V_44_fu_1079_p3;
wire   [2:0] tmp_34_fu_1121_p4;
wire   [6:0] add_ln321_2_fu_1141_p2;
wire   [6:0] add_ln137_fu_1151_p2;
wire   [6:0] add_ln137_1_fu_1162_p2;
wire   [4:0] or_ln321_fu_1186_p2;
wire   [6:0] add_ln137_2_fu_1239_p2;
wire   [6:0] add_ln137_3_fu_1250_p2;
wire   [16:0] trunc_ln1503_15_fu_1271_p1;
wire   [14:0] r_V_15_fu_1261_p4;
wire   [18:0] trunc_ln1503_16_fu_1293_p1;
wire   [12:0] r_V_16_fu_1283_p4;
wire   [21:0] r_V_17_fu_1305_p4;
wire   [31:0] r_V_23_fu_1315_p1;
wire   [31:0] ret_V_48_fu_1297_p3;
wire   [31:0] xor_ln1357_11_fu_1319_p2;
wire   [31:0] ret_V_47_fu_1275_p3;
wire   [6:0] trunc_ln1503_17_fu_1341_p1;
wire   [24:0] r_V_18_fu_1331_p4;
wire   [17:0] trunc_ln1503_18_fu_1363_p1;
wire   [13:0] r_V_19_fu_1353_p4;
wire   [28:0] r_V_20_fu_1375_p4;
wire   [31:0] r_V_24_fu_1385_p1;
wire   [31:0] ret_V_50_fu_1367_p3;
wire   [31:0] xor_ln1357_13_fu_1389_p2;
wire   [31:0] ret_V_49_fu_1345_p3;
wire   [31:0] ret_V_fu_1325_p2;
wire   [31:0] ret_V_38_fu_1395_p2;
wire   [31:0] add_ln209_18_fu_1407_p2;
wire   [31:0] add_ln209_21_fu_1418_p2;
wire   [31:0] add_ln209_20_fu_1428_p2;
wire   [31:0] add_ln209_25_fu_1444_p2;
wire   [4:0] or_ln321_7_fu_1453_p2;
wire   [4:0] or_ln321_8_fu_1467_p2;
wire   [4:0] or_ln321_9_fu_1487_p2;
wire   [4:0] or_ln321_10_fu_1501_p2;
wire   [4:0] or_ln321_11_fu_1515_p2;
wire   [4:0] or_ln321_12_fu_1529_p2;
wire   [3:0] xor_ln321_fu_1561_p2;
reg   [25:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
end

hash1_1_H_0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
H_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(H_0_V_address0),
    .ce0(H_0_V_ce0),
    .q0(H_0_V_q0)
);

hash1_1_K #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
K_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_address0),
    .ce0(K_ce0),
    .q0(K_q0)
);

hash1_1_message_V #(
    .DataWidth( 32 ),
    .AddressRange( 10000 ),
    .AddressWidth( 14 ))
message_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(message_V_address0),
    .ce0(message_V_ce0),
    .we0(message_V_we0),
    .d0(message_V_d0),
    .address1(message_V_address1),
    .ce1(message_V_ce1),
    .we1(message_V_we1),
    .d1(32'd256),
    .q1(message_V_q1)
);

hash1_1_M_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
M_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(M_V_address0),
    .ce0(M_V_ce0),
    .we0(M_V_we0),
    .d0(message_V_q1),
    .q0(M_V_q0)
);

hash1_1_H_V #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
H_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(H_V_address0),
    .ce0(H_V_ce0),
    .we0(H_V_we0),
    .d0(H_V_d0),
    .q0(H_V_q0),
    .address1(H_V_address1),
    .ce1(H_V_ce1),
    .we1(H_V_we1),
    .d1(H_V_d1),
    .q1(H_V_q1)
);

hash1_1_W_V #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W_V_address0),
    .ce0(W_V_ce0),
    .we0(W_V_we0),
    .d0(W_V_d0),
    .q0(W_V_q0),
    .address1(W_V_address1),
    .ce1(W_V_ce1),
    .we1(W_V_we1),
    .d1(M_V_q0),
    .q1(W_V_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        b_V_2_reg_549 <= a_V_reg_1682;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        b_V_2_reg_549 <= a_V_2_fu_1448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        c_V_2_reg_559 <= b_V_reg_1688;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        c_V_2_reg_559 <= b_V_2_reg_549;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        d_V_2_reg_570 <= c_V_reg_1704;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        d_V_2_reg_570 <= c_V_2_reg_559;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        f_V_2_reg_592 <= e_V_reg_1726;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        f_V_2_reg_592 <= e_V_2_fu_1439_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        g_V_2_reg_602 <= f_V_reg_1732;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        g_V_2_reg_602 <= f_V_2_reg_592;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        h_V_2_reg_613 <= H_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        h_V_2_reg_613 <= g_V_2_reg_602;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln114_fu_770_p2 == 1'd1))) begin
        i13_0_reg_647 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        i13_0_reg_647 <= i_13_reg_1899;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln105_fu_697_p2 == 1'd1))) begin
        i4_0_reg_503 <= i_11_reg_1598;
    end else if (((icmp_ln79_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i4_0_reg_503 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln104_fu_681_p2 == 1'd1))) begin
        i9_0_reg_526 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i9_0_reg_526 <= i_12_reg_1629;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_492 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_492 <= i_reg_1580;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln110_fu_753_p2 == 1'd1))) begin
        i_op_assign_2_reg_537 <= 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        i_op_assign_2_reg_537 <= i_14_reg_1840;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_op_assign_reg_515 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_op_assign_reg_515 <= j_reg_1611;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        j12_0_reg_635 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        j12_0_reg_635 <= j_2_reg_1758;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_0622_0_reg_581 <= d_V_reg_1710;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        p_0622_0_reg_581 <= d_V_2_reg_570;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_0657_0_reg_624 <= H_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        p_0657_0_reg_624 <= h_V_2_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_659 <= W_V_q1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        reg_659 <= W_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        T1_V_reg_1880 <= T1_V_fu_1434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        W_V_load_1_reg_1845 <= W_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        a_V_reg_1682 <= H_V_q0;
        b_V_reg_1688 <= H_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln114_fu_770_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        add_ln116_reg_1647 <= add_ln116_fu_776_p2;
        tmp_18_reg_1652[4 : 3] <= tmp_18_fu_782_p3[4 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln209_19_reg_1860 <= add_ln209_19_fu_1401_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        add_ln209_22_reg_1865 <= add_ln209_22_fu_1423_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln127_fu_905_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        add_ln209_2_reg_1820 <= add_ln209_2_fu_1213_p2;
        add_ln209_4_reg_1825 <= add_ln209_4_fu_1218_p2;
        add_ln209_5_reg_1830 <= add_ln209_5_fu_1223_p2;
        add_ln209_6_reg_1835 <= add_ln209_6_fu_1228_p2;
        i_14_reg_1840 <= i_14_fu_1233_p2;
        tmp_26_reg_1810[4 : 3] <= tmp_26_fu_1173_p3[4 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_697_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        add_ln321_reg_1616 <= add_ln321_fu_721_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        c_V_reg_1704 <= H_V_q1;
        d_V_reg_1710 <= H_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln127_fu_905_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        ch_V_reg_1763 <= ch_V_fu_935_p2;
        icmp_ln134_reg_1783 <= icmp_ln134_fu_1131_p2;
        maj_V_reg_1768 <= maj_V_fu_959_p2;
        ret_V_42_reg_1773 <= ret_V_42_fu_1037_p2;
        ret_V_46_reg_1778 <= ret_V_46_fu_1115_p2;
        zext_ln135_reg_1787[6 : 0] <= zext_ln135_fu_1137_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        e_V_reg_1726 <= H_V_q1;
        f_V_reg_1732 <= H_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        g_V_reg_1743 <= H_V_q1;
        h_V_reg_1749 <= H_V_q0;
        zext_ln116_2_reg_1738[5 : 4] <= zext_ln116_2_fu_901_p1[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_11_reg_1598 <= i_11_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_12_reg_1629 <= i_12_fu_759_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        i_13_reg_1899 <= i_13_fu_1555_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_1580 <= i_fu_670_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_2_reg_1758 <= j_2_fu_911_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_reg_1611 <= j_fu_703_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln110_fu_753_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        zext_ln111_reg_1634[3 : 0] <= zext_ln111_fu_765_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        zext_ln1598_reg_1603[4 : 0] <= zext_ln1598_fu_693_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln79_fu_664_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln80_reg_1585[3 : 0] <= zext_ln80_fu_676_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        H_0_V_ce0 = 1'b1;
    end else begin
        H_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        H_V_address0 = tmp_33_fu_1534_p3;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        H_V_address0 = tmp_31_fu_1506_p3;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        H_V_address0 = tmp_29_fu_1472_p3;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        H_V_address0 = tmp_27_fu_1192_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_address0 = tmp_25_fu_885_p3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        H_V_address0 = tmp_23_fu_857_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        H_V_address0 = tmp_21_fu_829_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        H_V_address0 = zext_ln116_fu_790_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        H_V_address0 = zext_ln111_reg_1634;
    end else begin
        H_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        H_V_address1 = zext_ln321_6_fu_1567_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        H_V_address1 = tmp_32_fu_1520_p3;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        H_V_address1 = tmp_30_fu_1492_p3;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        H_V_address1 = tmp_28_fu_1458_p3;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        H_V_address1 = zext_ln321_4_fu_1181_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        H_V_address1 = tmp_24_fu_871_p3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        H_V_address1 = tmp_22_fu_843_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        H_V_address1 = tmp_20_fu_815_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        H_V_address1 = tmp_19_fu_801_p3;
    end else begin
        H_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        H_V_ce0 = 1'b1;
    end else begin
        H_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        H_V_ce1 = 1'b1;
    end else begin
        H_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        H_V_d0 = add_ln209_7_fu_1543_p2;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        H_V_d0 = add_ln209_5_reg_1830;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        H_V_d0 = add_ln209_3_fu_1481_p2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        H_V_d0 = add_ln209_1_fu_1207_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        H_V_d0 = H_0_V_q0;
    end else begin
        H_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        H_V_d1 = add_ln209_6_reg_1835;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        H_V_d1 = add_ln209_4_reg_1825;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        H_V_d1 = add_ln209_2_reg_1820;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        H_V_d1 = add_ln209_fu_1201_p2;
    end else begin
        H_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state8) | ((icmp_ln127_fu_905_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)))) begin
        H_V_we0 = 1'b1;
    end else begin
        H_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state24) | ((icmp_ln127_fu_905_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)))) begin
        H_V_we1 = 1'b1;
    end else begin
        H_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        K_ce0 = 1'b1;
    end else begin
        K_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        M_V_address0 = zext_ln321_7_fu_1146_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        M_V_address0 = zext_ln321_5_fu_749_p1;
    end else begin
        M_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state14))) begin
        M_V_ce0 = 1'b1;
    end else begin
        M_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        M_V_we0 = 1'b1;
    end else begin
        M_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        W_V_address0 = W_V_addr_6_gep_fu_422_p3;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        W_V_address0 = zext_ln135_reg_1787;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        W_V_address0 = zext_ln137_5_fu_1245_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        W_V_address0 = zext_ln137_fu_1157_p1;
    end else begin
        W_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        W_V_address1 = zext_ln135_reg_1787;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        W_V_address1 = zext_ln137_6_fu_1256_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        W_V_address1 = zext_ln137_4_fu_1168_p1;
    end else begin
        W_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14))) begin
        W_V_ce0 = 1'b1;
    end else begin
        W_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state14))) begin
        W_V_ce1 = 1'b1;
    end else begin
        W_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln134_reg_1783 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        W_V_we0 = 1'b1;
    end else begin
        W_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        W_V_we1 = 1'b1;
    end else begin
        W_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln161_fu_1549_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_1549_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        message_V_address0 = zext_ln80_reg_1585;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        message_V_address0 = 64'd8;
    end else begin
        message_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        message_V_address1 = zext_ln106_fu_744_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        message_V_address1 = 64'd15;
    end else begin
        message_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        message_V_ce0 = 1'b1;
    end else begin
        message_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5))) begin
        message_V_ce1 = 1'b1;
    end else begin
        message_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        message_V_d0 = input_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        message_V_d0 = 32'd2147483648;
    end else begin
        message_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln79_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        message_V_we0 = 1'b1;
    end else begin
        message_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        message_V_we1 = 1'b1;
    end else begin
        message_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        outputlocation_V_ce0 = 1'b1;
    end else begin
        outputlocation_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        outputlocation_V_we0 = 1'b1;
    end else begin
        outputlocation_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln79_fu_664_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln104_fu_681_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln105_fu_697_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln110_fu_753_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln114_fu_770_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln127_fu_905_p2 == 1'd0) & (icmp_ln134_fu_1131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((icmp_ln134_fu_1131_p2 == 1'd0) & (icmp_ln127_fu_905_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln161_fu_1549_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_0_V_address0 = zext_ln111_fu_765_p1;

assign K_address0 = zext_ln135_reg_1787;

assign T1_V_fu_1434_p2 = (add_ln209_22_reg_1865 + add_ln209_20_fu_1428_p2);

assign W_V_addr_6_gep_fu_422_p3 = zext_ln135_reg_1787;

assign W_V_d0 = (add_ln209_19_reg_1860 + add_ln209_18_fu_1407_p2);

assign a_V_2_fu_1448_p2 = (add_ln209_25_fu_1444_p2 + maj_V_reg_1768);

assign add_ln106_fu_738_p2 = (shl_ln_fu_730_p3 + i4_0_reg_503);

assign add_ln116_fu_776_p2 = ($signed(i_op_assign_2_reg_537) + $signed(2'd3));

assign add_ln137_1_fu_1162_p2 = ($signed(7'd121) + $signed(j12_0_reg_635));

assign add_ln137_2_fu_1239_p2 = ($signed(7'd113) + $signed(j12_0_reg_635));

assign add_ln137_3_fu_1250_p2 = ($signed(7'd112) + $signed(j12_0_reg_635));

assign add_ln137_fu_1151_p2 = ($signed(7'd126) + $signed(j12_0_reg_635));

assign add_ln209_18_fu_1407_p2 = (W_V_load_1_reg_1845 + reg_659);

assign add_ln209_19_fu_1401_p2 = (ret_V_fu_1325_p2 + ret_V_38_fu_1395_p2);

assign add_ln209_1_fu_1207_p2 = (c_V_2_reg_559 + b_V_reg_1688);

assign add_ln209_20_fu_1428_p2 = (K_q0 + W_V_q0);

assign add_ln209_21_fu_1418_p2 = (ret_V_46_reg_1778 + p_0657_0_reg_624);

assign add_ln209_22_fu_1423_p2 = (add_ln209_21_fu_1418_p2 + ch_V_reg_1763);

assign add_ln209_25_fu_1444_p2 = (ret_V_42_reg_1773 + T1_V_reg_1880);

assign add_ln209_2_fu_1213_p2 = (d_V_2_reg_570 + c_V_reg_1704);

assign add_ln209_3_fu_1481_p2 = (p_0622_0_reg_581 + d_V_reg_1710);

assign add_ln209_4_fu_1218_p2 = (f_V_2_reg_592 + e_V_reg_1726);

assign add_ln209_5_fu_1223_p2 = (g_V_2_reg_602 + f_V_reg_1732);

assign add_ln209_6_fu_1228_p2 = (h_V_2_reg_613 + g_V_reg_1743);

assign add_ln209_7_fu_1543_p2 = (p_0657_0_reg_624 + h_V_reg_1749);

assign add_ln209_fu_1201_p2 = (b_V_2_reg_549 + a_V_reg_1682);

assign add_ln321_2_fu_1141_p2 = (zext_ln116_2_reg_1738 + j12_0_reg_635);

assign add_ln321_fu_721_p2 = (zext_ln321_fu_717_p1 + zext_ln1598_reg_1603);

assign and_ln26_2_fu_929_p2 = (xor_ln26_fu_923_p2 & h_V_2_reg_613);

assign and_ln26_fu_917_p2 = (g_V_2_reg_602 & f_V_2_reg_592);

assign and_ln31_2_fu_953_p2 = (d_V_2_reg_570 & c_V_2_reg_559);

assign and_ln31_fu_947_p2 = (xor_ln31_fu_941_p2 & b_V_2_reg_549);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ch_V_fu_935_p2 = (and_ln26_fu_917_p2 ^ and_ln26_2_fu_929_p2);

assign e_V_2_fu_1439_p2 = (p_0622_0_reg_581 + T1_V_reg_1880);

assign i_11_fu_687_p2 = (i4_0_reg_503 + 5'd1);

assign i_12_fu_759_p2 = (i9_0_reg_526 + 4'd1);

assign i_13_fu_1555_p2 = (i13_0_reg_647 + 4'd1);

assign i_14_fu_1233_p2 = (i_op_assign_2_reg_537 + 2'd1);

assign i_fu_670_p2 = (i_0_reg_492 + 4'd1);

assign icmp_ln104_fu_681_p2 = ((i4_0_reg_503 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_697_p2 = ((i_op_assign_reg_515 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_753_p2 = ((i9_0_reg_526 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_770_p2 = ((i_op_assign_2_reg_537 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_905_p2 = ((j12_0_reg_635 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_1131_p2 = ((tmp_34_fu_1121_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln161_fu_1549_p2 = ((i13_0_reg_647 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_664_p2 = ((i_0_reg_492 == 4'd9) ? 1'b1 : 1'b0);

assign input_V_address0 = zext_ln80_fu_676_p1;

assign j_2_fu_911_p2 = (j12_0_reg_635 + 7'd1);

assign j_fu_703_p2 = (i_op_assign_reg_515 + 2'd1);

assign maj_V_fu_959_p2 = (and_ln31_fu_947_p2 ^ and_ln31_2_fu_953_p2);

assign or_ln117_fu_795_p2 = (tmp_18_fu_782_p3 | 5'd1);

assign or_ln118_fu_810_p2 = (tmp_18_reg_1652 | 5'd2);

assign or_ln119_fu_824_p2 = (tmp_18_reg_1652 | 5'd3);

assign or_ln120_fu_838_p2 = (tmp_18_reg_1652 | 5'd4);

assign or_ln121_fu_852_p2 = (tmp_18_reg_1652 | 5'd5);

assign or_ln122_fu_866_p2 = (tmp_18_reg_1652 | 5'd6);

assign or_ln123_fu_880_p2 = (tmp_18_reg_1652 | 5'd7);

assign or_ln321_10_fu_1501_p2 = (tmp_26_reg_1810 | 5'd5);

assign or_ln321_11_fu_1515_p2 = (tmp_26_reg_1810 | 5'd6);

assign or_ln321_12_fu_1529_p2 = (tmp_26_reg_1810 | 5'd7);

assign or_ln321_7_fu_1453_p2 = (tmp_26_reg_1810 | 5'd2);

assign or_ln321_8_fu_1467_p2 = (tmp_26_reg_1810 | 5'd3);

assign or_ln321_9_fu_1487_p2 = (tmp_26_reg_1810 | 5'd4);

assign or_ln321_fu_1186_p2 = (tmp_26_fu_1173_p3 | 5'd1);

assign outputlocation_V_address0 = zext_ln162_fu_1572_p1;

assign outputlocation_V_d0 = H_V_q1;

assign r_V_11_fu_1009_p4 = {{b_V_2_reg_549[31:22]}};

assign r_V_12_fu_1043_p4 = {{f_V_2_reg_592[31:6]}};

assign r_V_13_fu_1065_p4 = {{f_V_2_reg_592[31:11]}};

assign r_V_14_fu_1087_p4 = {{f_V_2_reg_592[31:25]}};

assign r_V_15_fu_1261_p4 = {{reg_659[31:17]}};

assign r_V_16_fu_1283_p4 = {{reg_659[31:19]}};

assign r_V_17_fu_1305_p4 = {{reg_659[31:10]}};

assign r_V_18_fu_1331_p4 = {{W_V_q0[31:7]}};

assign r_V_19_fu_1353_p4 = {{W_V_q0[31:18]}};

assign r_V_20_fu_1375_p4 = {{W_V_q0[31:3]}};

assign r_V_23_fu_1315_p1 = r_V_17_fu_1305_p4;

assign r_V_24_fu_1385_p1 = r_V_20_fu_1375_p4;

assign r_V_fu_965_p4 = {{b_V_2_reg_549[31:2]}};

assign r_V_s_fu_987_p4 = {{b_V_2_reg_549[31:13]}};

assign ret_V_38_fu_1395_p2 = (xor_ln1357_13_fu_1389_p2 ^ ret_V_49_fu_1345_p3);

assign ret_V_39_fu_979_p3 = {{trunc_ln1503_fu_975_p1}, {r_V_fu_965_p4}};

assign ret_V_40_fu_1001_p3 = {{trunc_ln1503_10_fu_997_p1}, {r_V_s_fu_987_p4}};

assign ret_V_41_fu_1023_p3 = {{trunc_ln1503_11_fu_1019_p1}, {r_V_11_fu_1009_p4}};

assign ret_V_42_fu_1037_p2 = (xor_ln1357_fu_1031_p2 ^ ret_V_40_fu_1001_p3);

assign ret_V_43_fu_1057_p3 = {{trunc_ln1503_12_fu_1053_p1}, {r_V_12_fu_1043_p4}};

assign ret_V_44_fu_1079_p3 = {{trunc_ln1503_13_fu_1075_p1}, {r_V_13_fu_1065_p4}};

assign ret_V_45_fu_1101_p3 = {{trunc_ln1503_14_fu_1097_p1}, {r_V_14_fu_1087_p4}};

assign ret_V_46_fu_1115_p2 = (xor_ln1357_9_fu_1109_p2 ^ ret_V_44_fu_1079_p3);

assign ret_V_47_fu_1275_p3 = {{trunc_ln1503_15_fu_1271_p1}, {r_V_15_fu_1261_p4}};

assign ret_V_48_fu_1297_p3 = {{trunc_ln1503_16_fu_1293_p1}, {r_V_16_fu_1283_p4}};

assign ret_V_49_fu_1345_p3 = {{trunc_ln1503_17_fu_1341_p1}, {r_V_18_fu_1331_p4}};

assign ret_V_50_fu_1367_p3 = {{trunc_ln1503_18_fu_1363_p1}, {r_V_19_fu_1353_p4}};

assign ret_V_fu_1325_p2 = (xor_ln1357_11_fu_1319_p2 ^ ret_V_47_fu_1275_p3);

assign shl_ln_fu_730_p3 = {{trunc_ln106_fu_726_p1}, {4'd0}};

assign tmp_18_fu_782_p3 = {{add_ln116_fu_776_p2}, {3'd0}};

assign tmp_19_fu_801_p3 = {{59'd0}, {or_ln117_fu_795_p2}};

assign tmp_20_fu_815_p3 = {{59'd0}, {or_ln118_fu_810_p2}};

assign tmp_21_fu_829_p3 = {{59'd0}, {or_ln119_fu_824_p2}};

assign tmp_22_fu_843_p3 = {{59'd0}, {or_ln120_fu_838_p2}};

assign tmp_23_fu_857_p3 = {{59'd0}, {or_ln121_fu_852_p2}};

assign tmp_24_fu_871_p3 = {{59'd0}, {or_ln122_fu_866_p2}};

assign tmp_25_fu_885_p3 = {{59'd0}, {or_ln123_fu_880_p2}};

assign tmp_26_fu_1173_p3 = {{i_op_assign_2_reg_537}, {3'd0}};

assign tmp_27_fu_1192_p3 = {{59'd0}, {or_ln321_fu_1186_p2}};

assign tmp_28_fu_1458_p3 = {{59'd0}, {or_ln321_7_fu_1453_p2}};

assign tmp_29_fu_1472_p3 = {{59'd0}, {or_ln321_8_fu_1467_p2}};

assign tmp_30_fu_1492_p3 = {{59'd0}, {or_ln321_9_fu_1487_p2}};

assign tmp_31_fu_1506_p3 = {{59'd0}, {or_ln321_10_fu_1501_p2}};

assign tmp_32_fu_1520_p3 = {{59'd0}, {or_ln321_11_fu_1515_p2}};

assign tmp_33_fu_1534_p3 = {{59'd0}, {or_ln321_12_fu_1529_p2}};

assign tmp_34_fu_1121_p4 = {{j12_0_reg_635[6:4]}};

assign tmp_fu_709_p3 = {{i_op_assign_reg_515}, {4'd0}};

assign tmp_s_fu_894_p3 = {{add_ln116_reg_1647}, {4'd0}};

assign trunc_ln106_fu_726_p1 = i_op_assign_reg_515[0:0];

assign trunc_ln1503_10_fu_997_p1 = b_V_2_reg_549[12:0];

assign trunc_ln1503_11_fu_1019_p1 = b_V_2_reg_549[21:0];

assign trunc_ln1503_12_fu_1053_p1 = f_V_2_reg_592[5:0];

assign trunc_ln1503_13_fu_1075_p1 = f_V_2_reg_592[10:0];

assign trunc_ln1503_14_fu_1097_p1 = f_V_2_reg_592[24:0];

assign trunc_ln1503_15_fu_1271_p1 = reg_659[16:0];

assign trunc_ln1503_16_fu_1293_p1 = reg_659[18:0];

assign trunc_ln1503_17_fu_1341_p1 = W_V_q0[6:0];

assign trunc_ln1503_18_fu_1363_p1 = W_V_q0[17:0];

assign trunc_ln1503_fu_975_p1 = b_V_2_reg_549[1:0];

assign xor_ln1357_11_fu_1319_p2 = (ret_V_48_fu_1297_p3 ^ r_V_23_fu_1315_p1);

assign xor_ln1357_13_fu_1389_p2 = (ret_V_50_fu_1367_p3 ^ r_V_24_fu_1385_p1);

assign xor_ln1357_9_fu_1109_p2 = (ret_V_45_fu_1101_p3 ^ ret_V_43_fu_1057_p3);

assign xor_ln1357_fu_1031_p2 = (ret_V_41_fu_1023_p3 ^ ret_V_39_fu_979_p3);

assign xor_ln26_fu_923_p2 = (f_V_2_reg_592 ^ 32'd4294967295);

assign xor_ln31_fu_941_p2 = (d_V_2_reg_570 ^ c_V_2_reg_559);

assign xor_ln321_fu_1561_p2 = (i13_0_reg_647 ^ 4'd8);

assign zext_ln106_fu_744_p1 = add_ln106_fu_738_p2;

assign zext_ln111_fu_765_p1 = i9_0_reg_526;

assign zext_ln116_2_fu_901_p1 = tmp_s_fu_894_p3;

assign zext_ln116_fu_790_p1 = tmp_18_fu_782_p3;

assign zext_ln135_fu_1137_p1 = j12_0_reg_635;

assign zext_ln137_4_fu_1168_p1 = add_ln137_1_fu_1162_p2;

assign zext_ln137_5_fu_1245_p1 = add_ln137_2_fu_1239_p2;

assign zext_ln137_6_fu_1256_p1 = add_ln137_3_fu_1250_p2;

assign zext_ln137_fu_1157_p1 = add_ln137_fu_1151_p2;

assign zext_ln1598_fu_693_p1 = i4_0_reg_503;

assign zext_ln162_fu_1572_p1 = i13_0_reg_647;

assign zext_ln321_4_fu_1181_p1 = tmp_26_fu_1173_p3;

assign zext_ln321_5_fu_749_p1 = add_ln321_reg_1616;

assign zext_ln321_6_fu_1567_p1 = xor_ln321_fu_1561_p2;

assign zext_ln321_7_fu_1146_p1 = add_ln321_2_fu_1141_p2;

assign zext_ln321_fu_717_p1 = tmp_fu_709_p3;

assign zext_ln80_fu_676_p1 = i_0_reg_492;

always @ (posedge ap_clk) begin
    zext_ln80_reg_1585[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln1598_reg_1603[6:5] <= 2'b00;
    zext_ln111_reg_1634[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    tmp_18_reg_1652[2:0] <= 3'b000;
    zext_ln116_2_reg_1738[3:0] <= 4'b0000;
    zext_ln116_2_reg_1738[6] <= 1'b0;
    zext_ln135_reg_1787[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_26_reg_1810[2:0] <= 3'b000;
end

endmodule //hash1
