// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mineblock (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        agg_result_hash_V_address0,
        agg_result_hash_V_ce0,
        agg_result_hash_V_we0,
        agg_result_hash_V_d0,
        noncestart_V,
        version_0_V_read,
        prevhash_V_address0,
        prevhash_V_ce0,
        prevhash_V_q0,
        merkle_root_V_address0,
        merkle_root_V_ce0,
        merkle_root_V_q0,
        time_0_V_read,
        nbits_0_V_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] agg_result_hash_V_address0;
output   agg_result_hash_V_ce0;
output   agg_result_hash_V_we0;
output  [31:0] agg_result_hash_V_d0;
input  [31:0] noncestart_V;
input  [31:0] version_0_V_read;
output  [2:0] prevhash_V_address0;
output   prevhash_V_ce0;
input  [31:0] prevhash_V_q0;
output  [2:0] merkle_root_V_address0;
output   merkle_root_V_ce0;
input  [31:0] merkle_root_V_q0;
input  [31:0] time_0_V_read;
input  [31:0] nbits_0_V_read;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg agg_result_hash_V_ce0;
reg agg_result_hash_V_we0;
reg prevhash_V_ce0;
reg merkle_root_V_ce0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] difficulty_V_address0;
reg    difficulty_V_ce0;
wire   [0:0] difficulty_V_q0;
wire   [31:0] nonce_V_fu_299_p2;
reg   [31:0] nonce_V_reg_439;
wire   [3:0] i_fu_311_p2;
reg   [3:0] i_reg_447;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln159_fu_305_p2;
wire   [4:0] zext_ln164_fu_326_p1;
reg   [4:0] zext_ln164_reg_458;
wire    ap_CS_fsm_state4;
wire   [3:0] i_1_fu_336_p2;
reg   [3:0] i_1_reg_466;
wire   [0:0] icmp_ln164_fu_330_p2;
wire   [31:0] final_result_nonce_V_fu_357_p2;
reg   [31:0] final_result_nonce_V_reg_481;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln209_fu_364_p2;
reg   [0:0] icmp_ln209_reg_486;
wire    ap_CS_fsm_state11;
wire   [3:0] i_2_fu_370_p2;
reg   [3:0] i_2_reg_490;
wire   [3:0] j_fu_418_p2;
reg   [3:0] j_reg_514;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln214_fu_424_p1;
reg   [63:0] zext_ln214_reg_519;
wire   [0:0] icmp_ln213_fu_412_p2;
reg   [2:0] hash0_V_address0;
reg    hash0_V_ce0;
reg    hash0_V_we0;
wire   [31:0] hash0_V_q0;
reg   [4:0] blockheader_V_address0;
reg    blockheader_V_ce0;
reg    blockheader_V_we0;
reg   [31:0] blockheader_V_d0;
wire   [31:0] blockheader_V_q0;
reg   [4:0] blockheader_V_address1;
reg    blockheader_V_ce1;
reg    blockheader_V_we1;
reg   [31:0] blockheader_V_d1;
reg   [2:0] result_V_assign_address0;
reg    result_V_assign_ce0;
reg    result_V_assign_we0;
wire   [31:0] result_V_assign_q0;
wire    grp_hash1_1_fu_279_ap_start;
wire    grp_hash1_1_fu_279_ap_done;
wire    grp_hash1_1_fu_279_ap_idle;
wire    grp_hash1_1_fu_279_ap_ready;
wire   [4:0] grp_hash1_1_fu_279_input_V_address0;
wire    grp_hash1_1_fu_279_input_V_ce0;
wire   [2:0] grp_hash1_1_fu_279_outputlocation_V_address0;
wire    grp_hash1_1_fu_279_outputlocation_V_ce0;
wire    grp_hash1_1_fu_279_outputlocation_V_we0;
wire   [31:0] grp_hash1_1_fu_279_outputlocation_V_d0;
wire    grp_hash1_fu_289_ap_start;
wire    grp_hash1_fu_289_ap_done;
wire    grp_hash1_fu_289_ap_idle;
wire    grp_hash1_fu_289_ap_ready;
wire   [2:0] grp_hash1_fu_289_input_V_address0;
wire    grp_hash1_fu_289_input_V_ce0;
wire   [2:0] grp_hash1_fu_289_outputlocation_V_address0;
wire    grp_hash1_fu_289_outputlocation_V_ce0;
wire    grp_hash1_fu_289_outputlocation_V_we0;
wire   [31:0] grp_hash1_fu_289_outputlocation_V_d0;
reg   [3:0] i_0_reg_226;
wire    ap_CS_fsm_state3;
reg   [3:0] i1_0_reg_237;
wire    ap_CS_fsm_state5;
reg   [31:0] t_V_reg_248;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln887_fu_400_p2;
wire   [0:0] icmp_ln895_fu_406_p2;
reg   [3:0] i3_0_reg_257;
wire    ap_CS_fsm_state10;
reg   [3:0] j_0_reg_268;
wire    ap_CS_fsm_state14;
reg    grp_hash1_1_fu_279_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_hash1_fu_289_ap_start_reg;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln160_1_fu_317_p1;
wire   [63:0] zext_ln160_fu_322_p1;
wire   [63:0] zext_ln165_1_fu_342_p1;
wire   [63:0] zext_ln165_fu_352_p1;
wire   [63:0] zext_ln210_fu_382_p1;
wire   [63:0] zext_ln210_1_fu_387_p1;
wire   [4:0] add_ln165_fu_347_p2;
wire   [3:0] sub_ln210_fu_376_p2;
wire   [31:0] select_ln887_fu_392_p3;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_hash1_1_fu_279_ap_start_reg = 1'b0;
#0 grp_hash1_fu_289_ap_start_reg = 1'b0;
end

mineblock_difficubkb #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
difficulty_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(difficulty_V_address0),
    .ce0(difficulty_V_ce0),
    .q0(difficulty_V_q0)
);

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
hash0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hash0_V_address0),
    .ce0(hash0_V_ce0),
    .we0(hash0_V_we0),
    .d0(grp_hash1_1_fu_279_outputlocation_V_d0),
    .q0(hash0_V_q0)
);

mineblock_blockhecud #(
    .DataWidth( 32 ),
    .AddressRange( 20 ),
    .AddressWidth( 5 ))
blockheader_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blockheader_V_address0),
    .ce0(blockheader_V_ce0),
    .we0(blockheader_V_we0),
    .d0(blockheader_V_d0),
    .q0(blockheader_V_q0),
    .address1(blockheader_V_address1),
    .ce1(blockheader_V_ce1),
    .we1(blockheader_V_we1),
    .d1(blockheader_V_d1)
);

mineblock_hash0_V #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
result_V_assign_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_V_assign_address0),
    .ce0(result_V_assign_ce0),
    .we0(result_V_assign_we0),
    .d0(grp_hash1_fu_289_outputlocation_V_d0),
    .q0(result_V_assign_q0)
);

hash1_1 grp_hash1_1_fu_279(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hash1_1_fu_279_ap_start),
    .ap_done(grp_hash1_1_fu_279_ap_done),
    .ap_idle(grp_hash1_1_fu_279_ap_idle),
    .ap_ready(grp_hash1_1_fu_279_ap_ready),
    .input_V_address0(grp_hash1_1_fu_279_input_V_address0),
    .input_V_ce0(grp_hash1_1_fu_279_input_V_ce0),
    .input_V_q0(blockheader_V_q0),
    .outputlocation_V_address0(grp_hash1_1_fu_279_outputlocation_V_address0),
    .outputlocation_V_ce0(grp_hash1_1_fu_279_outputlocation_V_ce0),
    .outputlocation_V_we0(grp_hash1_1_fu_279_outputlocation_V_we0),
    .outputlocation_V_d0(grp_hash1_1_fu_279_outputlocation_V_d0)
);

hash1 grp_hash1_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hash1_fu_289_ap_start),
    .ap_done(grp_hash1_fu_289_ap_done),
    .ap_idle(grp_hash1_fu_289_ap_idle),
    .ap_ready(grp_hash1_fu_289_ap_ready),
    .input_V_address0(grp_hash1_fu_289_input_V_address0),
    .input_V_ce0(grp_hash1_fu_289_input_V_ce0),
    .input_V_q0(hash0_V_q0),
    .outputlocation_V_address0(grp_hash1_fu_289_outputlocation_V_address0),
    .outputlocation_V_ce0(grp_hash1_fu_289_outputlocation_V_ce0),
    .outputlocation_V_we0(grp_hash1_fu_289_outputlocation_V_we0),
    .outputlocation_V_d0(grp_hash1_fu_289_outputlocation_V_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hash1_1_fu_279_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_hash1_1_fu_279_ap_start_reg <= 1'b1;
        end else if ((grp_hash1_1_fu_279_ap_ready == 1'b1)) begin
            grp_hash1_1_fu_279_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hash1_fu_289_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_hash1_fu_289_ap_start_reg <= 1'b1;
        end else if ((grp_hash1_fu_289_ap_ready == 1'b1)) begin
            grp_hash1_fu_289_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln159_fu_305_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_237 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i1_0_reg_237 <= i_1_reg_466;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln895_fu_406_p2 == 1'd0) & (icmp_ln887_fu_400_p2 == 1'd0) & (icmp_ln209_reg_486 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i3_0_reg_257 <= i_2_reg_490;
    end else if (((1'b1 == ap_CS_fsm_state10) & (grp_hash1_fu_289_ap_done == 1'b1))) begin
        i3_0_reg_257 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_226 <= i_reg_447;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_226 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln209_reg_486 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln887_fu_400_p2 == 1'd1))) begin
        j_0_reg_268 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        j_0_reg_268 <= j_reg_514;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & ((icmp_ln209_reg_486 == 1'd1) | ((icmp_ln887_fu_400_p2 == 1'd0) & (icmp_ln895_fu_406_p2 == 1'd1))))) begin
        t_V_reg_248 <= final_result_nonce_V_reg_481;
    end else if (((icmp_ln164_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        t_V_reg_248 <= nonce_V_reg_439;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        final_result_nonce_V_reg_481 <= final_result_nonce_V_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_1_reg_466 <= i_1_fu_336_p2;
        zext_ln164_reg_458[3 : 0] <= zext_ln164_fu_326_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_2_reg_490 <= i_2_fu_370_p2;
        icmp_ln209_reg_486 <= icmp_ln209_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_447 <= i_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        j_reg_514 <= j_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        nonce_V_reg_439 <= nonce_V_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln213_fu_412_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        zext_ln214_reg_519[3 : 0] <= zext_ln214_fu_424_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        agg_result_hash_V_ce0 = 1'b1;
    end else begin
        agg_result_hash_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        agg_result_hash_V_we0 = 1'b1;
    end else begin
        agg_result_hash_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state13) & (icmp_ln213_fu_412_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln213_fu_412_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        blockheader_V_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        blockheader_V_address0 = zext_ln160_fu_322_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        blockheader_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        blockheader_V_address0 = grp_hash1_1_fu_279_input_V_address0;
    end else begin
        blockheader_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        blockheader_V_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blockheader_V_address1 = zext_ln165_fu_352_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        blockheader_V_address1 = 64'd18;
    end else begin
        blockheader_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        blockheader_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        blockheader_V_ce0 = grp_hash1_1_fu_279_input_V_ce0;
    end else begin
        blockheader_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        blockheader_V_ce1 = 1'b1;
    end else begin
        blockheader_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        blockheader_V_d0 = time_0_V_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        blockheader_V_d0 = prevhash_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        blockheader_V_d0 = version_0_V_read;
    end else begin
        blockheader_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        blockheader_V_d1 = final_result_nonce_V_fu_357_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blockheader_V_d1 = merkle_root_V_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        blockheader_V_d1 = nbits_0_V_read;
    end else begin
        blockheader_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln164_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        blockheader_V_we0 = 1'b1;
    end else begin
        blockheader_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6) | ((icmp_ln164_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        blockheader_V_we1 = 1'b1;
    end else begin
        blockheader_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        difficulty_V_ce0 = 1'b1;
    end else begin
        difficulty_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hash0_V_address0 = grp_hash1_fu_289_input_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hash0_V_address0 = grp_hash1_1_fu_279_outputlocation_V_address0;
    end else begin
        hash0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        hash0_V_ce0 = grp_hash1_fu_289_input_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hash0_V_ce0 = grp_hash1_1_fu_279_outputlocation_V_ce0;
    end else begin
        hash0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        hash0_V_we0 = grp_hash1_1_fu_279_outputlocation_V_we0;
    end else begin
        hash0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        merkle_root_V_ce0 = 1'b1;
    end else begin
        merkle_root_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        prevhash_V_ce0 = 1'b1;
    end else begin
        prevhash_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        result_V_assign_address0 = zext_ln214_fu_424_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        result_V_assign_address0 = zext_ln210_fu_382_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        result_V_assign_address0 = grp_hash1_fu_289_outputlocation_V_address0;
    end else begin
        result_V_assign_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11))) begin
        result_V_assign_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        result_V_assign_ce0 = grp_hash1_fu_289_outputlocation_V_ce0;
    end else begin
        result_V_assign_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        result_V_assign_we0 = grp_hash1_fu_289_outputlocation_V_we0;
    end else begin
        result_V_assign_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln159_fu_305_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln164_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_hash1_1_fu_279_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_hash1_fu_289_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & ((icmp_ln209_reg_486 == 1'd1) | ((icmp_ln887_fu_400_p2 == 1'd0) & (icmp_ln895_fu_406_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((icmp_ln209_reg_486 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln887_fu_400_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln213_fu_412_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln165_fu_347_p2 = (zext_ln164_reg_458 + 5'd9);

assign agg_result_hash_V_address0 = zext_ln214_reg_519;

assign agg_result_hash_V_d0 = result_V_assign_q0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = final_result_nonce_V_reg_481;

assign difficulty_V_address0 = zext_ln210_1_fu_387_p1;

assign final_result_nonce_V_fu_357_p2 = (t_V_reg_248 + 32'd1);

assign grp_hash1_1_fu_279_ap_start = grp_hash1_1_fu_279_ap_start_reg;

assign grp_hash1_fu_289_ap_start = grp_hash1_fu_289_ap_start_reg;

assign i_1_fu_336_p2 = (i1_0_reg_237 + 4'd1);

assign i_2_fu_370_p2 = (i3_0_reg_257 + 4'd1);

assign i_fu_311_p2 = (i_0_reg_226 + 4'd1);

assign icmp_ln159_fu_305_p2 = ((i_0_reg_226 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_330_p2 = ((i1_0_reg_237 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_364_p2 = ((i3_0_reg_257 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln213_fu_412_p2 = ((j_0_reg_268 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_400_p2 = ((result_V_assign_q0 < select_ln887_fu_392_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_406_p2 = ((result_V_assign_q0 > select_ln887_fu_392_p3) ? 1'b1 : 1'b0);

assign j_fu_418_p2 = (j_0_reg_268 + 4'd1);

assign merkle_root_V_address0 = zext_ln165_1_fu_342_p1;

assign nonce_V_fu_299_p2 = ($signed(noncestart_V) + $signed(32'd4294967295));

assign prevhash_V_address0 = zext_ln160_1_fu_317_p1;

assign select_ln887_fu_392_p3 = ((difficulty_V_q0[0:0] === 1'b1) ? 32'd65535 : 32'd0);

assign sub_ln210_fu_376_p2 = (4'd7 - i3_0_reg_257);

assign zext_ln160_1_fu_317_p1 = i_0_reg_226;

assign zext_ln160_fu_322_p1 = i_reg_447;

assign zext_ln164_fu_326_p1 = i1_0_reg_237;

assign zext_ln165_1_fu_342_p1 = i1_0_reg_237;

assign zext_ln165_fu_352_p1 = add_ln165_fu_347_p2;

assign zext_ln210_1_fu_387_p1 = i3_0_reg_257;

assign zext_ln210_fu_382_p1 = sub_ln210_fu_376_p2;

assign zext_ln214_fu_424_p1 = j_0_reg_268;

always @ (posedge ap_clk) begin
    zext_ln164_reg_458[4] <= 1'b0;
    zext_ln214_reg_519[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mineblock
