-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mineblock is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    agg_result_hash_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    agg_result_hash_V_ce0 : OUT STD_LOGIC;
    agg_result_hash_V_we0 : OUT STD_LOGIC;
    agg_result_hash_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    noncestart_V : IN STD_LOGIC_VECTOR (31 downto 0);
    version_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    prevhash_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    prevhash_V_ce0 : OUT STD_LOGIC;
    prevhash_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    merkle_root_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    merkle_root_V_ce0 : OUT STD_LOGIC;
    merkle_root_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    time_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    nbits_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of mineblock is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (14 downto 0) := "000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (14 downto 0) := "000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (14 downto 0) := "000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (14 downto 0) := "000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (14 downto 0) := "000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (14 downto 0) := "000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (14 downto 0) := "000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (14 downto 0) := "000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (14 downto 0) := "001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (14 downto 0) := "010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_11 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010001";
    constant ap_const_lv64_12 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010010";
    constant ap_const_lv64_13 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal difficulty_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal difficulty_V_ce0 : STD_LOGIC;
    signal difficulty_V_q0 : STD_LOGIC_VECTOR (28 downto 0);
    signal nonce_V_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal nonce_V_reg_496 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_356_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_504 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln32_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln37_fu_371_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln37_reg_515 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_1_fu_381_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_523 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln37_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal final_result_nonce_V_fu_402_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal final_result_nonce_V_reg_548 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln85_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal i_2_fu_415_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_2_reg_557 : STD_LOGIC_VECTOR (3 downto 0);
    signal count_fu_457_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal icmp_ln887_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_475_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_589 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal zext_ln97_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln97_reg_594 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln96_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hash0_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal hash0_V_ce0 : STD_LOGIC;
    signal hash0_V_we0 : STD_LOGIC;
    signal hash0_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal hash0_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal blockheader_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal blockheader_V_ce0 : STD_LOGIC;
    signal blockheader_V_we0 : STD_LOGIC;
    signal blockheader_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal blockheader_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal blockheader_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal blockheader_V_ce1 : STD_LOGIC;
    signal blockheader_V_we1 : STD_LOGIC;
    signal blockheader_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal result_V_ce0 : STD_LOGIC;
    signal result_V_we0 : STD_LOGIC;
    signal result_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hash1_1_fu_324_ap_start : STD_LOGIC;
    signal grp_hash1_1_fu_324_ap_done : STD_LOGIC;
    signal grp_hash1_1_fu_324_ap_idle : STD_LOGIC;
    signal grp_hash1_1_fu_324_ap_ready : STD_LOGIC;
    signal grp_hash1_1_fu_324_input_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_hash1_1_fu_324_input_V_ce0 : STD_LOGIC;
    signal grp_hash1_1_fu_324_outputlocation_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_hash1_1_fu_324_outputlocation_V_ce0 : STD_LOGIC;
    signal grp_hash1_1_fu_324_outputlocation_V_we0 : STD_LOGIC;
    signal grp_hash1_1_fu_324_outputlocation_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_hash1_fu_334_ap_start : STD_LOGIC;
    signal grp_hash1_fu_334_ap_done : STD_LOGIC;
    signal grp_hash1_fu_334_ap_idle : STD_LOGIC;
    signal grp_hash1_fu_334_ap_ready : STD_LOGIC;
    signal grp_hash1_fu_334_input_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_hash1_fu_334_input_V_ce0 : STD_LOGIC;
    signal grp_hash1_fu_334_outputlocation_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_hash1_fu_334_outputlocation_V_ce0 : STD_LOGIC;
    signal grp_hash1_fu_334_outputlocation_V_we0 : STD_LOGIC;
    signal grp_hash1_fu_334_outputlocation_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_247 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i1_0_reg_258 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal t_V_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln895_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln94_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal count_0_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal i2_0_reg_290 : STD_LOGIC_VECTOR (3 downto 0);
    signal count_0_be_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_313 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_hash1_1_fu_324_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_hash1_fu_334_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal zext_ln33_1_fu_362_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln38_1_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln38_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_fu_427_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln86_1_fu_432_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln38_fu_392_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln86_fu_421_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln887_fu_437_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln887_fu_441_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (14 downto 0);

    component hash1_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_V_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        input_V_ce0 : OUT STD_LOGIC;
        input_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        outputlocation_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        outputlocation_V_ce0 : OUT STD_LOGIC;
        outputlocation_V_we0 : OUT STD_LOGIC;
        outputlocation_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hash1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_V_ce0 : OUT STD_LOGIC;
        input_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        outputlocation_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        outputlocation_V_ce0 : OUT STD_LOGIC;
        outputlocation_V_we0 : OUT STD_LOGIC;
        outputlocation_V_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mineblock_difficubkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component mineblock_hash0_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mineblock_blockhecud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    difficulty_V_U : component mineblock_difficubkb
    generic map (
        DataWidth => 29,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => difficulty_V_address0,
        ce0 => difficulty_V_ce0,
        q0 => difficulty_V_q0);

    hash0_V_U : component mineblock_hash0_V
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => hash0_V_address0,
        ce0 => hash0_V_ce0,
        we0 => hash0_V_we0,
        d0 => hash0_V_d0,
        q0 => hash0_V_q0);

    blockheader_V_U : component mineblock_blockhecud
    generic map (
        DataWidth => 32,
        AddressRange => 20,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => blockheader_V_address0,
        ce0 => blockheader_V_ce0,
        we0 => blockheader_V_we0,
        d0 => blockheader_V_d0,
        q0 => blockheader_V_q0,
        address1 => blockheader_V_address1,
        ce1 => blockheader_V_ce1,
        we1 => blockheader_V_we1,
        d1 => blockheader_V_d1);

    result_V_U : component mineblock_hash0_V
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => result_V_address0,
        ce0 => result_V_ce0,
        we0 => result_V_we0,
        d0 => result_V_d0,
        q0 => result_V_q0);

    grp_hash1_1_fu_324 : component hash1_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_hash1_1_fu_324_ap_start,
        ap_done => grp_hash1_1_fu_324_ap_done,
        ap_idle => grp_hash1_1_fu_324_ap_idle,
        ap_ready => grp_hash1_1_fu_324_ap_ready,
        input_V_address0 => grp_hash1_1_fu_324_input_V_address0,
        input_V_ce0 => grp_hash1_1_fu_324_input_V_ce0,
        input_V_q0 => blockheader_V_q0,
        outputlocation_V_address0 => grp_hash1_1_fu_324_outputlocation_V_address0,
        outputlocation_V_ce0 => grp_hash1_1_fu_324_outputlocation_V_ce0,
        outputlocation_V_we0 => grp_hash1_1_fu_324_outputlocation_V_we0,
        outputlocation_V_d0 => grp_hash1_1_fu_324_outputlocation_V_d0);

    grp_hash1_fu_334 : component hash1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_hash1_fu_334_ap_start,
        ap_done => grp_hash1_fu_334_ap_done,
        ap_idle => grp_hash1_fu_334_ap_idle,
        ap_ready => grp_hash1_fu_334_ap_ready,
        input_V_address0 => grp_hash1_fu_334_input_V_address0,
        input_V_ce0 => grp_hash1_fu_334_input_V_ce0,
        input_V_q0 => hash0_V_q0,
        outputlocation_V_address0 => grp_hash1_fu_334_outputlocation_V_address0,
        outputlocation_V_ce0 => grp_hash1_fu_334_outputlocation_V_ce0,
        outputlocation_V_we0 => grp_hash1_fu_334_outputlocation_V_we0,
        outputlocation_V_d0 => grp_hash1_fu_334_outputlocation_V_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_hash1_1_fu_324_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_hash1_1_fu_324_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_hash1_1_fu_324_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hash1_1_fu_324_ap_ready = ap_const_logic_1)) then 
                    grp_hash1_1_fu_324_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_hash1_fu_334_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_hash1_fu_334_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_hash1_fu_334_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_hash1_fu_334_ap_ready = ap_const_logic_1)) then 
                    grp_hash1_fu_334_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_0_be_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln85_reg_553 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                if (((icmp_ln895_fu_451_p2 = ap_const_lv1_0) and (icmp_ln887_fu_445_p2 = ap_const_lv1_0))) then 
                    count_0_be_reg_301 <= count_0_reg_278;
                elsif ((icmp_ln887_fu_445_p2 = ap_const_lv1_1)) then 
                    count_0_be_reg_301 <= count_fu_457_p2;
                end if;
            end if; 
        end if;
    end process;

    count_0_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                count_0_reg_278 <= count_0_be_reg_301;
            elsif (((grp_hash1_fu_334_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                count_0_reg_278 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i1_0_reg_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln32_fu_350_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i1_0_reg_258 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i1_0_reg_258 <= i_1_reg_523;
            end if; 
        end if;
    end process;

    i2_0_reg_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                i2_0_reg_290 <= i_2_reg_557;
            elsif (((grp_hash1_fu_334_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                i2_0_reg_290 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    i_0_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_0_reg_247 <= i_reg_504;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_247 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    j_0_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (((icmp_ln94_fu_463_p2 = ap_const_lv1_1) and (icmp_ln85_reg_553 = ap_const_lv1_1)) or ((icmp_ln887_fu_445_p2 = ap_const_lv1_0) and (icmp_ln94_fu_463_p2 = ap_const_lv1_1) and (icmp_ln895_fu_451_p2 = ap_const_lv1_1))))) then 
                j_0_reg_313 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                j_0_reg_313 <= j_reg_589;
            end if; 
        end if;
    end process;

    t_V_reg_269_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (((icmp_ln94_fu_463_p2 = ap_const_lv1_0) and (icmp_ln85_reg_553 = ap_const_lv1_1)) or ((icmp_ln94_fu_463_p2 = ap_const_lv1_0) and (icmp_ln887_fu_445_p2 = ap_const_lv1_0) and (icmp_ln895_fu_451_p2 = ap_const_lv1_1))))) then 
                t_V_reg_269 <= final_result_nonce_V_reg_548;
            elsif (((icmp_ln37_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                t_V_reg_269 <= nonce_V_reg_496;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                final_result_nonce_V_reg_548 <= final_result_nonce_V_fu_402_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_1_reg_523 <= i_1_fu_381_p2;
                    zext_ln37_reg_515(3 downto 0) <= zext_ln37_fu_371_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                i_2_reg_557 <= i_2_fu_415_p2;
                icmp_ln85_reg_553 <= icmp_ln85_fu_409_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_504 <= i_fu_356_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                j_reg_589 <= j_fu_475_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                nonce_V_reg_496 <= nonce_V_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln96_fu_469_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    zext_ln97_reg_594(3 downto 0) <= zext_ln97_fu_481_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln37_reg_515(4) <= '0';
    zext_ln97_reg_594(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln32_fu_350_p2, ap_CS_fsm_state4, icmp_ln37_fu_375_p2, icmp_ln85_reg_553, ap_CS_fsm_state12, icmp_ln887_fu_445_p2, ap_CS_fsm_state14, icmp_ln96_fu_469_p2, grp_hash1_1_fu_324_ap_done, grp_hash1_fu_334_ap_done, icmp_ln895_fu_451_p2, icmp_ln94_fu_463_p2, ap_CS_fsm_state10, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln32_fu_350_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln37_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_hash1_1_fu_324_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_hash1_fu_334_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (((icmp_ln94_fu_463_p2 = ap_const_lv1_1) and (icmp_ln85_reg_553 = ap_const_lv1_1)) or ((icmp_ln887_fu_445_p2 = ap_const_lv1_0) and (icmp_ln94_fu_463_p2 = ap_const_lv1_1) and (icmp_ln895_fu_451_p2 = ap_const_lv1_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (((icmp_ln94_fu_463_p2 = ap_const_lv1_0) and (icmp_ln85_reg_553 = ap_const_lv1_1)) or ((icmp_ln94_fu_463_p2 = ap_const_lv1_0) and (icmp_ln887_fu_445_p2 = ap_const_lv1_0) and (icmp_ln895_fu_451_p2 = ap_const_lv1_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln96_fu_469_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln38_fu_392_p2 <= std_logic_vector(unsigned(zext_ln37_reg_515) + unsigned(ap_const_lv5_9));
    agg_result_hash_V_address0 <= zext_ln97_reg_594(3 - 1 downto 0);

    agg_result_hash_V_ce0_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            agg_result_hash_V_ce0 <= ap_const_logic_1;
        else 
            agg_result_hash_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_hash_V_d0 <= result_V_q0;

    agg_result_hash_V_we0_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            agg_result_hash_V_we0 <= ap_const_logic_1;
        else 
            agg_result_hash_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14, icmp_ln96_fu_469_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln96_fu_469_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14, icmp_ln96_fu_469_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln96_fu_469_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= final_result_nonce_V_reg_548;

    blockheader_V_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state4, grp_hash1_1_fu_324_input_V_address0, ap_CS_fsm_state3, ap_CS_fsm_state8, zext_ln33_fu_367_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blockheader_V_address0 <= ap_const_lv64_11(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            blockheader_V_address0 <= zext_ln33_fu_367_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            blockheader_V_address0 <= ap_const_lv64_0(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            blockheader_V_address0 <= grp_hash1_1_fu_324_input_V_address0;
        else 
            blockheader_V_address0 <= "XXXXX";
        end if; 
    end process;


    blockheader_V_address1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5, zext_ln38_fu_397_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            blockheader_V_address1 <= ap_const_lv64_13(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            blockheader_V_address1 <= zext_ln38_fu_397_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blockheader_V_address1 <= ap_const_lv64_12(5 - 1 downto 0);
        else 
            blockheader_V_address1 <= "XXXXX";
        end if; 
    end process;


    blockheader_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, grp_hash1_1_fu_324_input_V_ce0, ap_CS_fsm_state3, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            blockheader_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            blockheader_V_ce0 <= grp_hash1_1_fu_324_input_V_ce0;
        else 
            blockheader_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    blockheader_V_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            blockheader_V_ce1 <= ap_const_logic_1;
        else 
            blockheader_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    blockheader_V_d0_assign_proc : process(ap_CS_fsm_state1, version_0_V_read, prevhash_V_q0, time_0_V_read, ap_CS_fsm_state4, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blockheader_V_d0 <= time_0_V_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            blockheader_V_d0 <= prevhash_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            blockheader_V_d0 <= version_0_V_read;
        else 
            blockheader_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    blockheader_V_d1_assign_proc : process(merkle_root_V_q0, nbits_0_V_read, ap_CS_fsm_state4, final_result_nonce_V_fu_402_p2, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            blockheader_V_d1 <= final_result_nonce_V_fu_402_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            blockheader_V_d1 <= merkle_root_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            blockheader_V_d1 <= nbits_0_V_read;
        else 
            blockheader_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    blockheader_V_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln37_fu_375_p2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln37_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            blockheader_V_we0 <= ap_const_logic_1;
        else 
            blockheader_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    blockheader_V_we1_assign_proc : process(ap_CS_fsm_state4, icmp_ln37_fu_375_p2, ap_CS_fsm_state6, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((icmp_ln37_fu_375_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            blockheader_V_we1 <= ap_const_logic_1;
        else 
            blockheader_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    count_fu_457_p2 <= std_logic_vector(unsigned(count_0_reg_278) + unsigned(ap_const_lv32_1));
    difficulty_V_address0 <= zext_ln86_1_fu_432_p1(3 - 1 downto 0);

    difficulty_V_ce0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            difficulty_V_ce0 <= ap_const_logic_1;
        else 
            difficulty_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    final_result_nonce_V_fu_402_p2 <= std_logic_vector(unsigned(t_V_reg_269) + unsigned(ap_const_lv32_1));
    grp_hash1_1_fu_324_ap_start <= grp_hash1_1_fu_324_ap_start_reg;
    grp_hash1_fu_334_ap_start <= grp_hash1_fu_334_ap_start_reg;

    hash0_V_address0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_1_fu_324_outputlocation_V_address0, grp_hash1_fu_334_input_V_address0, ap_CS_fsm_state10, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hash0_V_address0 <= ap_const_lv64_0(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            hash0_V_address0 <= grp_hash1_fu_334_input_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            hash0_V_address0 <= grp_hash1_1_fu_324_outputlocation_V_address0;
        else 
            hash0_V_address0 <= "XXX";
        end if; 
    end process;


    hash0_V_ce0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_1_fu_324_outputlocation_V_ce0, grp_hash1_fu_334_input_V_ce0, ap_CS_fsm_state10, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hash0_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            hash0_V_ce0 <= grp_hash1_fu_334_input_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            hash0_V_ce0 <= grp_hash1_1_fu_324_outputlocation_V_ce0;
        else 
            hash0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    hash0_V_d0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_1_fu_324_outputlocation_V_d0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hash0_V_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            hash0_V_d0 <= grp_hash1_1_fu_324_outputlocation_V_d0;
        else 
            hash0_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    hash0_V_we0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_1_fu_324_outputlocation_V_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            hash0_V_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            hash0_V_we0 <= grp_hash1_1_fu_324_outputlocation_V_we0;
        else 
            hash0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    i_1_fu_381_p2 <= std_logic_vector(unsigned(i1_0_reg_258) + unsigned(ap_const_lv4_1));
    i_2_fu_415_p2 <= std_logic_vector(unsigned(i2_0_reg_290) + unsigned(ap_const_lv4_1));
    i_fu_356_p2 <= std_logic_vector(unsigned(i_0_reg_247) + unsigned(ap_const_lv4_1));
    icmp_ln32_fu_350_p2 <= "1" when (i_0_reg_247 = ap_const_lv4_8) else "0";
    icmp_ln37_fu_375_p2 <= "1" when (i1_0_reg_258 = ap_const_lv4_8) else "0";
    icmp_ln85_fu_409_p2 <= "1" when (i2_0_reg_290 = ap_const_lv4_8) else "0";
    icmp_ln887_fu_445_p2 <= "1" when (unsigned(result_V_q0) < unsigned(zext_ln887_fu_441_p1)) else "0";
    icmp_ln895_fu_451_p2 <= "1" when (unsigned(result_V_q0) > unsigned(zext_ln887_fu_441_p1)) else "0";
    icmp_ln94_fu_463_p2 <= "1" when (count_0_reg_278 = ap_const_lv32_8) else "0";
    icmp_ln96_fu_469_p2 <= "1" when (j_0_reg_313 = ap_const_lv4_8) else "0";
    j_fu_475_p2 <= std_logic_vector(unsigned(j_0_reg_313) + unsigned(ap_const_lv4_1));
    merkle_root_V_address0 <= zext_ln38_1_fu_387_p1(3 - 1 downto 0);

    merkle_root_V_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            merkle_root_V_ce0 <= ap_const_logic_1;
        else 
            merkle_root_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nonce_V_fu_344_p2 <= std_logic_vector(unsigned(noncestart_V) + unsigned(ap_const_lv32_FFFFFFFF));
    prevhash_V_address0 <= zext_ln33_1_fu_362_p1(3 - 1 downto 0);

    prevhash_V_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            prevhash_V_ce0 <= ap_const_logic_1;
        else 
            prevhash_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    result_V_address0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state11, ap_CS_fsm_state14, zext_ln97_fu_481_p1, grp_hash1_fu_334_outputlocation_V_address0, ap_CS_fsm_state10, zext_ln86_fu_427_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            result_V_address0 <= zext_ln97_fu_481_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            result_V_address0 <= zext_ln86_fu_427_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            result_V_address0 <= ap_const_lv64_0(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            result_V_address0 <= grp_hash1_fu_334_outputlocation_V_address0;
        else 
            result_V_address0 <= "XXX";
        end if; 
    end process;


    result_V_ce0_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state11, ap_CS_fsm_state14, grp_hash1_fu_334_outputlocation_V_ce0, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            result_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            result_V_ce0 <= grp_hash1_fu_334_outputlocation_V_ce0;
        else 
            result_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    result_V_d0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_fu_334_outputlocation_V_d0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            result_V_d0 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            result_V_d0 <= grp_hash1_fu_334_outputlocation_V_d0;
        else 
            result_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    result_V_we0_assign_proc : process(ap_CS_fsm_state6, grp_hash1_fu_334_outputlocation_V_we0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            result_V_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            result_V_we0 <= grp_hash1_fu_334_outputlocation_V_we0;
        else 
            result_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln887_fu_437_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(difficulty_V_q0),31));

    sub_ln86_fu_421_p2 <= std_logic_vector(unsigned(ap_const_lv4_7) - unsigned(i2_0_reg_290));
    zext_ln33_1_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_247),64));
    zext_ln33_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_504),64));
    zext_ln37_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_0_reg_258),5));
    zext_ln38_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_0_reg_258),64));
    zext_ln38_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln38_fu_392_p2),64));
    zext_ln86_1_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i2_0_reg_290),64));
    zext_ln86_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln86_fu_421_p2),64));
    zext_ln887_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln887_fu_437_p1),32));
    zext_ln97_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_313),64));
end behav;
