// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> dut::ap_ST_fsm_state1 = "1";
const sc_lv<16> dut::ap_ST_fsm_state2 = "10";
const sc_lv<16> dut::ap_ST_fsm_state3 = "100";
const sc_lv<16> dut::ap_ST_fsm_state4 = "1000";
const sc_lv<16> dut::ap_ST_fsm_state5 = "10000";
const sc_lv<16> dut::ap_ST_fsm_state6 = "100000";
const sc_lv<16> dut::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> dut::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> dut::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> dut::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> dut::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> dut::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> dut::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> dut::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> dut::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> dut::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> dut::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dut::ap_const_lv32_1 = "1";
const sc_lv<32> dut::ap_const_lv32_2 = "10";
const sc_lv<1> dut::ap_const_lv1_0 = "0";
const sc_lv<32> dut::ap_const_lv32_3 = "11";
const sc_lv<1> dut::ap_const_lv1_1 = "1";
const sc_lv<32> dut::ap_const_lv32_4 = "100";
const sc_lv<32> dut::ap_const_lv32_6 = "110";
const sc_lv<32> dut::ap_const_lv32_8 = "1000";
const sc_lv<32> dut::ap_const_lv32_9 = "1001";
const sc_lv<32> dut::ap_const_lv32_A = "1010";
const sc_lv<32> dut::ap_const_lv32_B = "1011";
const sc_lv<32> dut::ap_const_lv32_C = "1100";
const sc_lv<32> dut::ap_const_lv32_D = "1101";
const sc_lv<32> dut::ap_const_lv32_E = "1110";
const sc_lv<32> dut::ap_const_lv32_F = "1111";
const sc_lv<32> dut::ap_const_lv32_5 = "101";
const sc_lv<4> dut::ap_const_lv4_0 = "0000";
const sc_lv<32> dut::ap_const_lv32_7 = "111";
const sc_lv<64> dut::ap_const_lv64_7 = "111";
const sc_lv<64> dut::ap_const_lv64_6 = "110";
const sc_lv<64> dut::ap_const_lv64_5 = "101";
const sc_lv<64> dut::ap_const_lv64_4 = "100";
const sc_lv<64> dut::ap_const_lv64_3 = "11";
const sc_lv<64> dut::ap_const_lv64_2 = "10";
const sc_lv<64> dut::ap_const_lv64_1 = "1";
const sc_lv<64> dut::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<4> dut::ap_const_lv4_8 = "1000";
const sc_lv<4> dut::ap_const_lv4_1 = "1";
const bool dut::ap_const_boolean_1 = true;

dut::dut(sc_module_name name) : sc_module(name), mVcdFile(0) {
    prevhash_V_U = new mineblock_hash0_V("prevhash_V_U");
    prevhash_V_U->clk(ap_clk);
    prevhash_V_U->reset(ap_rst);
    prevhash_V_U->address0(prevhash_V_address0);
    prevhash_V_U->ce0(prevhash_V_ce0);
    prevhash_V_U->we0(prevhash_V_we0);
    prevhash_V_U->d0(strm_in_V_V_dout);
    prevhash_V_U->q0(prevhash_V_q0);
    merkle_root_V_U = new mineblock_hash0_V("merkle_root_V_U");
    merkle_root_V_U->clk(ap_clk);
    merkle_root_V_U->reset(ap_rst);
    merkle_root_V_U->address0(merkle_root_V_address0);
    merkle_root_V_U->ce0(merkle_root_V_ce0);
    merkle_root_V_U->we0(merkle_root_V_we0);
    merkle_root_V_U->d0(strm_in_V_V_dout);
    merkle_root_V_U->q0(merkle_root_V_q0);
    output_hash_V_U = new mineblock_hash0_V("output_hash_V_U");
    output_hash_V_U->clk(ap_clk);
    output_hash_V_U->reset(ap_rst);
    output_hash_V_U->address0(output_hash_V_address0);
    output_hash_V_U->ce0(output_hash_V_ce0);
    output_hash_V_U->we0(output_hash_V_we0);
    output_hash_V_U->d0(p_1_q0);
    output_hash_V_U->q0(output_hash_V_q0);
    p_1_U = new mineblock_hash0_V("p_1_U");
    p_1_U->clk(ap_clk);
    p_1_U->reset(ap_rst);
    p_1_U->address0(p_1_address0);
    p_1_U->ce0(p_1_ce0);
    p_1_U->we0(p_1_we0);
    p_1_U->d0(grp_mineblock_fu_238_agg_result_hash_V_d0);
    p_1_U->q0(p_1_q0);
    grp_mineblock_fu_238 = new mineblock("grp_mineblock_fu_238");
    grp_mineblock_fu_238->ap_clk(ap_clk);
    grp_mineblock_fu_238->ap_rst(ap_rst);
    grp_mineblock_fu_238->ap_start(grp_mineblock_fu_238_ap_start);
    grp_mineblock_fu_238->ap_done(grp_mineblock_fu_238_ap_done);
    grp_mineblock_fu_238->ap_idle(grp_mineblock_fu_238_ap_idle);
    grp_mineblock_fu_238->ap_ready(grp_mineblock_fu_238_ap_ready);
    grp_mineblock_fu_238->agg_result_hash_V_address0(grp_mineblock_fu_238_agg_result_hash_V_address0);
    grp_mineblock_fu_238->agg_result_hash_V_ce0(grp_mineblock_fu_238_agg_result_hash_V_ce0);
    grp_mineblock_fu_238->agg_result_hash_V_we0(grp_mineblock_fu_238_agg_result_hash_V_we0);
    grp_mineblock_fu_238->agg_result_hash_V_d0(grp_mineblock_fu_238_agg_result_hash_V_d0);
    grp_mineblock_fu_238->noncestart_V(tmp_V_reg_307);
    grp_mineblock_fu_238->version_0_V_read(tmp_V_15_reg_312);
    grp_mineblock_fu_238->prevhash_V_address0(grp_mineblock_fu_238_prevhash_V_address0);
    grp_mineblock_fu_238->prevhash_V_ce0(grp_mineblock_fu_238_prevhash_V_ce0);
    grp_mineblock_fu_238->prevhash_V_q0(prevhash_V_q0);
    grp_mineblock_fu_238->merkle_root_V_address0(grp_mineblock_fu_238_merkle_root_V_address0);
    grp_mineblock_fu_238->merkle_root_V_ce0(grp_mineblock_fu_238_merkle_root_V_ce0);
    grp_mineblock_fu_238->merkle_root_V_q0(merkle_root_V_q0);
    grp_mineblock_fu_238->time_0_V_read(tmp_V_16_reg_333);
    grp_mineblock_fu_238->nbits_0_V_read(tmp_V_17_reg_338);
    grp_mineblock_fu_238->ap_return(grp_mineblock_fu_238_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( strm_in_V_V_empty_n );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( icmp_ln37_fu_256_p2 );

    SC_METHOD(thread_ap_block_state4);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( icmp_ln43_fu_273_p2 );

    SC_METHOD(thread_ap_block_state7);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( icmp_ln24_fu_295_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_grp_mineblock_fu_238_ap_start);
    sensitive << ( grp_mineblock_fu_238_ap_start_reg );

    SC_METHOD(thread_i_15_fu_279_p2);
    sensitive << ( i4_0_reg_216 );

    SC_METHOD(thread_i_fu_262_p2);
    sensitive << ( i2_0_reg_205 );

    SC_METHOD(thread_icmp_ln24_fu_295_p2);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( p_i0_0_i_reg_227 );

    SC_METHOD(thread_icmp_ln37_fu_256_p2);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );
    sensitive << ( i2_0_reg_205 );

    SC_METHOD(thread_icmp_ln43_fu_273_p2);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );
    sensitive << ( i4_0_reg_216 );

    SC_METHOD(thread_merkle_root_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_merkle_root_V_address0 );
    sensitive << ( zext_ln44_fu_285_p1 );

    SC_METHOD(thread_merkle_root_V_ce0);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_merkle_root_V_ce0 );

    SC_METHOD(thread_merkle_root_V_we0);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );

    SC_METHOD(thread_output_hash_V_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln24_reg_348 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_hash_V_ce0);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_hash_V_we0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_p_1_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln24_fu_290_p1 );
    sensitive << ( grp_mineblock_fu_238_agg_result_hash_V_address0 );

    SC_METHOD(thread_p_1_ce0);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_agg_result_hash_V_ce0 );

    SC_METHOD(thread_p_1_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_agg_result_hash_V_we0 );

    SC_METHOD(thread_p_i0_fu_301_p2);
    sensitive << ( p_i0_0_i_reg_227 );

    SC_METHOD(thread_prevhash_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_prevhash_V_address0 );
    sensitive << ( zext_ln38_fu_268_p1 );

    SC_METHOD(thread_prevhash_V_ce0);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_prevhash_V_ce0 );

    SC_METHOD(thread_prevhash_V_we0);
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );

    SC_METHOD(thread_strm_in_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_strm_in_V_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_strm_out_V_V_blk_n);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_strm_out_V_V_din);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( output_nonce_V_reg_343 );
    sensitive << ( output_hash_V_q0 );

    SC_METHOD(thread_strm_out_V_V_write);
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_zext_ln24_fu_290_p1);
    sensitive << ( p_i0_0_i_reg_227 );

    SC_METHOD(thread_zext_ln38_fu_268_p1);
    sensitive << ( i2_0_reg_205 );

    SC_METHOD(thread_zext_ln44_fu_285_p1);
    sensitive << ( i4_0_reg_216 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( strm_in_V_V_empty_n );
    sensitive << ( strm_out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_273_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln24_fu_295_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_mineblock_fu_238_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000001";
    grp_mineblock_fu_238_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, strm_in_V_V_dout, "(port)strm_in_V_V_dout");
    sc_trace(mVcdFile, strm_in_V_V_empty_n, "(port)strm_in_V_V_empty_n");
    sc_trace(mVcdFile, strm_in_V_V_read, "(port)strm_in_V_V_read");
    sc_trace(mVcdFile, strm_out_V_V_din, "(port)strm_out_V_V_din");
    sc_trace(mVcdFile, strm_out_V_V_full_n, "(port)strm_out_V_V_full_n");
    sc_trace(mVcdFile, strm_out_V_V_write, "(port)strm_out_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, strm_in_V_V_blk_n, "strm_in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln37_fu_256_p2, "icmp_ln37_fu_256_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln43_fu_273_p2, "icmp_ln43_fu_273_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, strm_out_V_V_blk_n, "strm_out_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln24_fu_295_p2, "icmp_ln24_fu_295_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_V_reg_307, "tmp_V_reg_307");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_V_15_reg_312, "tmp_V_15_reg_312");
    sc_trace(mVcdFile, i_fu_262_p2, "i_fu_262_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, i_15_fu_279_p2, "i_15_fu_279_p2");
    sc_trace(mVcdFile, ap_block_state4, "ap_block_state4");
    sc_trace(mVcdFile, tmp_V_16_reg_333, "tmp_V_16_reg_333");
    sc_trace(mVcdFile, tmp_V_17_reg_338, "tmp_V_17_reg_338");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_return, "grp_mineblock_fu_238_ap_return");
    sc_trace(mVcdFile, output_nonce_V_reg_343, "output_nonce_V_reg_343");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_ready, "grp_mineblock_fu_238_ap_ready");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_done, "grp_mineblock_fu_238_ap_done");
    sc_trace(mVcdFile, zext_ln24_fu_290_p1, "zext_ln24_fu_290_p1");
    sc_trace(mVcdFile, zext_ln24_reg_348, "zext_ln24_reg_348");
    sc_trace(mVcdFile, ap_block_state7, "ap_block_state7");
    sc_trace(mVcdFile, p_i0_fu_301_p2, "p_i0_fu_301_p2");
    sc_trace(mVcdFile, p_i0_reg_356, "p_i0_reg_356");
    sc_trace(mVcdFile, prevhash_V_address0, "prevhash_V_address0");
    sc_trace(mVcdFile, prevhash_V_ce0, "prevhash_V_ce0");
    sc_trace(mVcdFile, prevhash_V_we0, "prevhash_V_we0");
    sc_trace(mVcdFile, prevhash_V_q0, "prevhash_V_q0");
    sc_trace(mVcdFile, merkle_root_V_address0, "merkle_root_V_address0");
    sc_trace(mVcdFile, merkle_root_V_ce0, "merkle_root_V_ce0");
    sc_trace(mVcdFile, merkle_root_V_we0, "merkle_root_V_we0");
    sc_trace(mVcdFile, merkle_root_V_q0, "merkle_root_V_q0");
    sc_trace(mVcdFile, output_hash_V_address0, "output_hash_V_address0");
    sc_trace(mVcdFile, output_hash_V_ce0, "output_hash_V_ce0");
    sc_trace(mVcdFile, output_hash_V_we0, "output_hash_V_we0");
    sc_trace(mVcdFile, output_hash_V_q0, "output_hash_V_q0");
    sc_trace(mVcdFile, p_1_address0, "p_1_address0");
    sc_trace(mVcdFile, p_1_ce0, "p_1_ce0");
    sc_trace(mVcdFile, p_1_we0, "p_1_we0");
    sc_trace(mVcdFile, p_1_q0, "p_1_q0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_start, "grp_mineblock_fu_238_ap_start");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_idle, "grp_mineblock_fu_238_ap_idle");
    sc_trace(mVcdFile, grp_mineblock_fu_238_agg_result_hash_V_address0, "grp_mineblock_fu_238_agg_result_hash_V_address0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_agg_result_hash_V_ce0, "grp_mineblock_fu_238_agg_result_hash_V_ce0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_agg_result_hash_V_we0, "grp_mineblock_fu_238_agg_result_hash_V_we0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_agg_result_hash_V_d0, "grp_mineblock_fu_238_agg_result_hash_V_d0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_prevhash_V_address0, "grp_mineblock_fu_238_prevhash_V_address0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_prevhash_V_ce0, "grp_mineblock_fu_238_prevhash_V_ce0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_merkle_root_V_address0, "grp_mineblock_fu_238_merkle_root_V_address0");
    sc_trace(mVcdFile, grp_mineblock_fu_238_merkle_root_V_ce0, "grp_mineblock_fu_238_merkle_root_V_ce0");
    sc_trace(mVcdFile, i2_0_reg_205, "i2_0_reg_205");
    sc_trace(mVcdFile, i4_0_reg_216, "i4_0_reg_216");
    sc_trace(mVcdFile, p_i0_0_i_reg_227, "p_i0_0_i_reg_227");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_mineblock_fu_238_ap_start_reg, "grp_mineblock_fu_238_ap_start_reg");
    sc_trace(mVcdFile, zext_ln38_fu_268_p1, "zext_ln38_fu_268_p1");
    sc_trace(mVcdFile, zext_ln44_fu_285_p1, "zext_ln44_fu_285_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dut.hdltvin.dat");
    mHdltvoutHandle.open("dut.hdltvout.dat");
}

dut::~dut() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete prevhash_V_U;
    delete merkle_root_V_U;
    delete output_hash_V_U;
    delete p_1_U;
    delete grp_mineblock_fu_238;
}

void dut::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_mineblock_fu_238_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
            grp_mineblock_fu_238_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_mineblock_fu_238_ap_ready.read())) {
            grp_mineblock_fu_238_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
        i2_0_reg_205 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
        i2_0_reg_205 = i_fu_262_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) && 
         esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_1))) {
        i4_0_reg_216 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
                !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
        i4_0_reg_216 = i_15_fu_279_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_i0_0_i_reg_227 = p_i0_reg_356.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(grp_mineblock_fu_238_ap_done.read(), ap_const_logic_1))) {
        p_i0_0_i_reg_227 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_mineblock_fu_238_ap_done.read(), ap_const_logic_1))) {
        output_nonce_V_reg_343 = grp_mineblock_fu_238_ap_return.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read())))) {
        p_i0_reg_356 = p_i0_fu_301_p2.read();
        zext_ln24_reg_348 = zext_ln24_fu_290_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
        tmp_V_15_reg_312 = strm_in_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
        tmp_V_16_reg_333 = strm_in_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
        tmp_V_17_reg_338 = strm_in_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
        tmp_V_reg_307 = strm_in_V_V_dout.read();
    }
}

void dut::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dut::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void dut::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void dut::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void dut::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dut::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dut::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dut::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void dut::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dut::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dut::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dut::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dut::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dut::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dut::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dut::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void dut::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()));
}

void dut::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()));
}

void dut::thread_ap_block_state4() {
    ap_block_state4 = ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())));
}

void dut::thread_ap_block_state7() {
    ap_block_state7 = (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read()));
}

void dut::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut::thread_grp_mineblock_fu_238_ap_start() {
    grp_mineblock_fu_238_ap_start = grp_mineblock_fu_238_ap_start_reg.read();
}

void dut::thread_i_15_fu_279_p2() {
    i_15_fu_279_p2 = (!i4_0_reg_216.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i4_0_reg_216.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut::thread_i_fu_262_p2() {
    i_fu_262_p2 = (!i2_0_reg_205.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i2_0_reg_205.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut::thread_icmp_ln24_fu_295_p2() {
    icmp_ln24_fu_295_p2 = (!p_i0_0_i_reg_227.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(p_i0_0_i_reg_227.read() == ap_const_lv4_8);
}

void dut::thread_icmp_ln37_fu_256_p2() {
    icmp_ln37_fu_256_p2 = (!i2_0_reg_205.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_205.read() == ap_const_lv4_8);
}

void dut::thread_icmp_ln43_fu_273_p2() {
    icmp_ln43_fu_273_p2 = (!i4_0_reg_216.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i4_0_reg_216.read() == ap_const_lv4_8);
}

void dut::thread_merkle_root_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        merkle_root_V_address0 =  (sc_lv<3>) (zext_ln44_fu_285_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        merkle_root_V_address0 = grp_mineblock_fu_238_merkle_root_V_address0.read();
    } else {
        merkle_root_V_address0 = "XXX";
    }
}

void dut::thread_merkle_root_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
        merkle_root_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        merkle_root_V_ce0 = grp_mineblock_fu_238_merkle_root_V_ce0.read();
    } else {
        merkle_root_V_ce0 = ap_const_logic_0;
    }
}

void dut::thread_merkle_root_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
         !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
        merkle_root_V_we0 = ap_const_logic_1;
    } else {
        merkle_root_V_we0 = ap_const_logic_0;
    }
}

void dut::thread_output_hash_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (zext_ln24_reg_348.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_hash_V_address0 =  (sc_lv<3>) (ap_const_lv64_7);
    } else {
        output_hash_V_address0 = "XXX";
    }
}

void dut::thread_output_hash_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        output_hash_V_ce0 = ap_const_logic_1;
    } else {
        output_hash_V_ce0 = ap_const_logic_0;
    }
}

void dut::thread_output_hash_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_hash_V_we0 = ap_const_logic_1;
    } else {
        output_hash_V_we0 = ap_const_logic_0;
    }
}

void dut::thread_p_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_1_address0 =  (sc_lv<3>) (zext_ln24_fu_290_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_1_address0 = grp_mineblock_fu_238_agg_result_hash_V_address0.read();
    } else {
        p_1_address0 = "XXX";
    }
}

void dut::thread_p_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read())))) {
        p_1_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_1_ce0 = grp_mineblock_fu_238_agg_result_hash_V_ce0.read();
    } else {
        p_1_ce0 = ap_const_logic_0;
    }
}

void dut::thread_p_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_1_we0 = grp_mineblock_fu_238_agg_result_hash_V_we0.read();
    } else {
        p_1_we0 = ap_const_logic_0;
    }
}

void dut::thread_p_i0_fu_301_p2() {
    p_i0_fu_301_p2 = (!p_i0_0_i_reg_227.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(p_i0_0_i_reg_227.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut::thread_prevhash_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        prevhash_V_address0 =  (sc_lv<3>) (zext_ln38_fu_268_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        prevhash_V_address0 = grp_mineblock_fu_238_prevhash_V_address0.read();
    } else {
        prevhash_V_address0 = "XXX";
    }
}

void dut::thread_prevhash_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
        prevhash_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        prevhash_V_ce0 = grp_mineblock_fu_238_prevhash_V_ce0.read();
    } else {
        prevhash_V_ce0 = ap_const_logic_0;
    }
}

void dut::thread_prevhash_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
        prevhash_V_we0 = ap_const_logic_1;
    } else {
        prevhash_V_we0 = ap_const_logic_0;
    }
}

void dut::thread_strm_in_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        strm_in_V_V_blk_n = strm_in_V_V_empty_n.read();
    } else {
        strm_in_V_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_in_V_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
          !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && 
          !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
          !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))))) {
        strm_in_V_V_read = ap_const_logic_1;
    } else {
        strm_in_V_V_read = ap_const_logic_0;
    }
}

void dut::thread_strm_out_V_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        strm_out_V_V_blk_n = strm_out_V_V_full_n.read();
    } else {
        strm_out_V_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_out_V_V_din() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)))) {
        strm_out_V_V_din = output_hash_V_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read())))) {
        strm_out_V_V_din = output_nonce_V_reg_343.read();
    } else {
        strm_out_V_V_din =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut::thread_strm_out_V_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1)))) {
        strm_out_V_V_write = ap_const_logic_1;
    } else {
        strm_out_V_V_write = ap_const_logic_0;
    }
}

void dut::thread_zext_ln24_fu_290_p1() {
    zext_ln24_fu_290_p1 = esl_zext<64,4>(p_i0_0_i_reg_227.read());
}

void dut::thread_zext_ln38_fu_268_p1() {
    zext_ln38_fu_268_p1 = esl_zext<64,4>(i2_0_reg_205.read());
}

void dut::thread_zext_ln44_fu_285_p1() {
    zext_ln44_fu_285_p1 = esl_zext<64,4>(i4_0_reg_216.read());
}

void dut::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(icmp_ln37_fu_256_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && !((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_273_p2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(icmp_ln43_fu_273_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, strm_in_V_V_empty_n.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(strm_in_V_V_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_mineblock_fu_238_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln24_fu_295_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, strm_out_V_V_full_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln24_fu_295_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(strm_out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void dut::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_V_V_dout\" :  \"" << strm_in_V_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_V_V_empty_n\" :  \"" << strm_in_V_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_in_V_V_read\" :  \"" << strm_in_V_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_V_din\" :  \"" << strm_out_V_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_out_V_V_full_n\" :  \"" << strm_out_V_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_V_write\" :  \"" << strm_out_V_V_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

